// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/payment/v1/payment.proto

package paymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateInvoiceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CheckoutGroupId string                 `protobuf:"bytes,1,opt,name=checkout_group_id,json=checkoutGroupId,proto3" json:"checkout_group_id,omitempty"`
	Amount          float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateInvoiceRequest) Reset() {
	*x = CreateInvoiceRequest{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceRequest) ProtoMessage() {}

func (x *CreateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceRequest.ProtoReflect.Descriptor instead.
func (*CreateInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInvoiceRequest) GetCheckoutGroupId() string {
	if x != nil {
		return x.CheckoutGroupId
	}
	return ""
}

func (x *CreateInvoiceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateInvoiceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	InvoiceUrl    string                 `protobuf:"bytes,2,opt,name=invoice_url,json=invoiceUrl,proto3" json:"invoice_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceResponse) Reset() {
	*x = CreateInvoiceResponse{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceResponse) ProtoMessage() {}

func (x *CreateInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceResponse.ProtoReflect.Descriptor instead.
func (*CreateInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInvoiceResponse) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *CreateInvoiceResponse) GetInvoiceUrl() string {
	if x != nil {
		return x.InvoiceUrl
	}
	return ""
}

type DisburseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithdrawId    string                 `protobuf:"bytes,1,opt,name=withdraw_id,json=withdrawId,proto3" json:"withdraw_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	BankCode      string                 `protobuf:"bytes,3,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	AccountNumber string                 `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountName   string                 `protobuf:"bytes,5,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisburseRequest) Reset() {
	*x = DisburseRequest{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisburseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisburseRequest) ProtoMessage() {}

func (x *DisburseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisburseRequest.ProtoReflect.Descriptor instead.
func (*DisburseRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *DisburseRequest) GetWithdrawId() string {
	if x != nil {
		return x.WithdrawId
	}
	return ""
}

func (x *DisburseRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DisburseRequest) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *DisburseRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *DisburseRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

type DisburseResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DisbursementId string                 `protobuf:"bytes,1,opt,name=disbursement_id,json=disbursementId,proto3" json:"disbursement_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DisburseResponse) Reset() {
	*x = DisburseResponse{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisburseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisburseResponse) ProtoMessage() {}

func (x *DisburseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisburseResponse.ProtoReflect.Descriptor instead.
func (*DisburseResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *DisburseResponse) GetDisbursementId() string {
	if x != nil {
		return x.DisbursementId
	}
	return ""
}

var File_proto_payment_v1_payment_proto protoreflect.FileDescriptor

const file_proto_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/payment/v1/payment.proto\x12\n" +
	"payment.v1\"|\n" +
	"\x14CreateInvoiceRequest\x12*\n" +
	"\x11checkout_group_id\x18\x01 \x01(\tR\x0fcheckoutGroupId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"W\n" +
	"\x15CreateInvoiceResponse\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x1f\n" +
	"\vinvoice_url\x18\x02 \x01(\tR\n" +
	"invoiceUrl\"\xb1\x01\n" +
	"\x0fDisburseRequest\x12\x1f\n" +
	"\vwithdraw_id\x18\x01 \x01(\tR\n" +
	"withdrawId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1b\n" +
	"\tbank_code\x18\x03 \x01(\tR\bbankCode\x12%\n" +
	"\x0eaccount_number\x18\x04 \x01(\tR\raccountNumber\x12!\n" +
	"\faccount_name\x18\x05 \x01(\tR\vaccountName\";\n" +
	"\x10DisburseResponse\x12'\n" +
	"\x0fdisbursement_id\x18\x01 \x01(\tR\x0edisbursementId2\xad\x01\n" +
	"\x0ePaymentService\x12T\n" +
	"\rCreateInvoice\x12 .payment.v1.CreateInvoiceRequest\x1a!.payment.v1.CreateInvoiceResponse\x12E\n" +
	"\bDisburse\x12\x1b.payment.v1.DisburseRequest\x1a\x1c.payment.v1.DisburseResponseB0Z.erdinhrmwn/bangunin/proto/payment/v1;paymentv1b\x06proto3"

var (
	file_proto_payment_v1_payment_proto_rawDescOnce sync.Once
	file_proto_payment_v1_payment_proto_rawDescData []byte
)

func file_proto_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_proto_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_proto_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_v1_payment_proto_rawDesc), len(file_proto_payment_v1_payment_proto_rawDesc)))
	})
	return file_proto_payment_v1_payment_proto_rawDescData
}

var file_proto_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_payment_v1_payment_proto_goTypes = []any{
	(*CreateInvoiceRequest)(nil),  // 0: payment.v1.CreateInvoiceRequest
	(*CreateInvoiceResponse)(nil), // 1: payment.v1.CreateInvoiceResponse
	(*DisburseRequest)(nil),       // 2: payment.v1.DisburseRequest
	(*DisburseResponse)(nil),      // 3: payment.v1.DisburseResponse
}
var file_proto_payment_v1_payment_proto_depIdxs = []int32{
	0, // 0: payment.v1.PaymentService.CreateInvoice:input_type -> payment.v1.CreateInvoiceRequest
	2, // 1: payment.v1.PaymentService.Disburse:input_type -> payment.v1.DisburseRequest
	1, // 2: payment.v1.PaymentService.CreateInvoice:output_type -> payment.v1.CreateInvoiceResponse
	3, // 3: payment.v1.PaymentService.Disburse:output_type -> payment.v1.DisburseResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_payment_v1_payment_proto_init() }
func file_proto_payment_v1_payment_proto_init() {
	if File_proto_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_v1_payment_proto_rawDesc), len(file_proto_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_proto_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_proto_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_proto_payment_v1_payment_proto = out.File
	file_proto_payment_v1_payment_proto_goTypes = nil
	file_proto_payment_v1_payment_proto_depIdxs = nil
}
