with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
packages:
  erdinhrmwn/bangunin/internal/domain/repository:
    interfaces:
      UserRepository:
      AuthRepository:
      SupplierRepository:
      SupplierDocumentRepository:
      SupplierBankAccountRepository:
      NotificationRepository:
      AuditLogRepository:
  erdinhrmwn/bangunin/internal/domain/service:
    interfaces:
      EmailEnqueuer:
      StorageService:
      MediaEnqueuer:
