// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockShipmentRepository is an autogenerated mock type for the ShipmentRepository type
type MockShipmentRepository struct {
	mock.Mock
}

type MockShipmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShipmentRepository) EXPECT() *MockShipmentRepository_Expecter {
	return &MockShipmentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, s
func (_m *MockShipmentRepository) Create(ctx context.Context, s *entity.Shipment) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Shipment) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockShipmentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockShipmentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s *entity.Shipment
func (_e *MockShipmentRepository_Expecter) Create(ctx interface{}, s interface{}) *MockShipmentRepository_Create_Call {
	return &MockShipmentRepository_Create_Call{Call: _e.mock.On("Create", ctx, s)}
}

func (_c *MockShipmentRepository_Create_Call) Run(run func(ctx context.Context, s *entity.Shipment)) *MockShipmentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Shipment))
	})
	return _c
}

func (_c *MockShipmentRepository_Create_Call) Return(_a0 error) *MockShipmentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShipmentRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Shipment) error) *MockShipmentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOrderID provides a mock function with given fields: ctx, orderID
func (_m *MockShipmentRepository) FindByOrderID(ctx context.Context, orderID uuid.UUID) (*entity.Shipment, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrderID")
	}

	var r0 *entity.Shipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Shipment, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Shipment); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Shipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockShipmentRepository_FindByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrderID'
type MockShipmentRepository_FindByOrderID_Call struct {
	*mock.Call
}

// FindByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockShipmentRepository_Expecter) FindByOrderID(ctx interface{}, orderID interface{}) *MockShipmentRepository_FindByOrderID_Call {
	return &MockShipmentRepository_FindByOrderID_Call{Call: _e.mock.On("FindByOrderID", ctx, orderID)}
}

func (_c *MockShipmentRepository_FindByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockShipmentRepository_FindByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockShipmentRepository_FindByOrderID_Call) Return(_a0 *entity.Shipment, _a1 error) *MockShipmentRepository_FindByOrderID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockShipmentRepository_FindByOrderID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Shipment, error)) *MockShipmentRepository_FindByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, s
func (_m *MockShipmentRepository) Update(ctx context.Context, s *entity.Shipment) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Shipment) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockShipmentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockShipmentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - s *entity.Shipment
func (_e *MockShipmentRepository_Expecter) Update(ctx interface{}, s interface{}) *MockShipmentRepository_Update_Call {
	return &MockShipmentRepository_Update_Call{Call: _e.mock.On("Update", ctx, s)}
}

func (_c *MockShipmentRepository_Update_Call) Run(run func(ctx context.Context, s *entity.Shipment)) *MockShipmentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Shipment))
	})
	return _c
}

func (_c *MockShipmentRepository_Update_Call) Return(_a0 error) *MockShipmentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShipmentRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Shipment) error) *MockShipmentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockShipmentRepository creates a new instance of MockShipmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShipmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShipmentRepository {
	mock := &MockShipmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
