// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockLedgerEntryRepository is an autogenerated mock type for the LedgerEntryRepository type
type MockLedgerEntryRepository struct {
	mock.Mock
}

type MockLedgerEntryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLedgerEntryRepository) EXPECT() *MockLedgerEntryRepository_Expecter {
	return &MockLedgerEntryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, e
func (_m *MockLedgerEntryRepository) Create(ctx context.Context, e *entity.LedgerEntry) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.LedgerEntry) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLedgerEntryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLedgerEntryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - e *entity.LedgerEntry
func (_e *MockLedgerEntryRepository_Expecter) Create(ctx interface{}, e interface{}) *MockLedgerEntryRepository_Create_Call {
	return &MockLedgerEntryRepository_Create_Call{Call: _e.mock.On("Create", ctx, e)}
}

func (_c *MockLedgerEntryRepository_Create_Call) Run(run func(ctx context.Context, e *entity.LedgerEntry)) *MockLedgerEntryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.LedgerEntry))
	})
	return _c
}

func (_c *MockLedgerEntryRepository_Create_Call) Return(_a0 error) *MockLedgerEntryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLedgerEntryRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.LedgerEntry) error) *MockLedgerEntryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListBySupplier provides a mock function with given fields: ctx, supplierID, page, perPage
func (_m *MockLedgerEntryRepository) ListBySupplier(ctx context.Context, supplierID uuid.UUID, page int, perPage int) ([]*entity.LedgerEntry, int, error) {
	ret := _m.Called(ctx, supplierID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for ListBySupplier")
	}

	var r0 []*entity.LedgerEntry
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*entity.LedgerEntry, int, error)); ok {
		return rf(ctx, supplierID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*entity.LedgerEntry); ok {
		r0 = rf(ctx, supplierID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.LedgerEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, supplierID, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, supplierID, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLedgerEntryRepository_ListBySupplier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBySupplier'
type MockLedgerEntryRepository_ListBySupplier_Call struct {
	*mock.Call
}

// ListBySupplier is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID uuid.UUID
//   - page int
//   - perPage int
func (_e *MockLedgerEntryRepository_Expecter) ListBySupplier(ctx interface{}, supplierID interface{}, page interface{}, perPage interface{}) *MockLedgerEntryRepository_ListBySupplier_Call {
	return &MockLedgerEntryRepository_ListBySupplier_Call{Call: _e.mock.On("ListBySupplier", ctx, supplierID, page, perPage)}
}

func (_c *MockLedgerEntryRepository_ListBySupplier_Call) Run(run func(ctx context.Context, supplierID uuid.UUID, page int, perPage int)) *MockLedgerEntryRepository_ListBySupplier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockLedgerEntryRepository_ListBySupplier_Call) Return(_a0 []*entity.LedgerEntry, _a1 int, _a2 error) *MockLedgerEntryRepository_ListBySupplier_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockLedgerEntryRepository_ListBySupplier_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*entity.LedgerEntry, int, error)) *MockLedgerEntryRepository_ListBySupplier_Call {
	_c.Call.Return(run)
	return _c
}

// SumByType provides a mock function with given fields: ctx, entryType, from, to
func (_m *MockLedgerEntryRepository) SumByType(ctx context.Context, entryType string, from time.Time, to time.Time) (float64, error) {
	ret := _m.Called(ctx, entryType, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SumByType")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) (float64, error)); ok {
		return rf(ctx, entryType, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) float64); ok {
		r0 = rf(ctx, entryType, from, to)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, entryType, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLedgerEntryRepository_SumByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumByType'
type MockLedgerEntryRepository_SumByType_Call struct {
	*mock.Call
}

// SumByType is a helper method to define mock.On call
//   - ctx context.Context
//   - entryType string
//   - from time.Time
//   - to time.Time
func (_e *MockLedgerEntryRepository_Expecter) SumByType(ctx interface{}, entryType interface{}, from interface{}, to interface{}) *MockLedgerEntryRepository_SumByType_Call {
	return &MockLedgerEntryRepository_SumByType_Call{Call: _e.mock.On("SumByType", ctx, entryType, from, to)}
}

func (_c *MockLedgerEntryRepository_SumByType_Call) Run(run func(ctx context.Context, entryType string, from time.Time, to time.Time)) *MockLedgerEntryRepository_SumByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockLedgerEntryRepository_SumByType_Call) Return(_a0 float64, _a1 error) *MockLedgerEntryRepository_SumByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLedgerEntryRepository_SumByType_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) (float64, error)) *MockLedgerEntryRepository_SumByType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLedgerEntryRepository creates a new instance of MockLedgerEntryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLedgerEntryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLedgerEntryRepository {
	mock := &MockLedgerEntryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
