// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockAuthRepository is an autogenerated mock type for the AuthRepository type
type MockAuthRepository struct {
	mock.Mock
}

type MockAuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepository) EXPECT() *MockAuthRepository_Expecter {
	return &MockAuthRepository_Expecter{mock: &_m.Mock}
}

// BlacklistJTI provides a mock function with given fields: ctx, jti, ttl
func (_m *MockAuthRepository) BlacklistJTI(ctx context.Context, jti string, ttl time.Duration) error {
	ret := _m.Called(ctx, jti, ttl)

	if len(ret) == 0 {
		panic("no return value specified for BlacklistJTI")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(ctx, jti, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthRepository_BlacklistJTI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlacklistJTI'
type MockAuthRepository_BlacklistJTI_Call struct {
	*mock.Call
}

// BlacklistJTI is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
//   - ttl time.Duration
func (_e *MockAuthRepository_Expecter) BlacklistJTI(ctx interface{}, jti interface{}, ttl interface{}) *MockAuthRepository_BlacklistJTI_Call {
	return &MockAuthRepository_BlacklistJTI_Call{Call: _e.mock.On("BlacklistJTI", ctx, jti, ttl)}
}

func (_c *MockAuthRepository_BlacklistJTI_Call) Run(run func(ctx context.Context, jti string, ttl time.Duration)) *MockAuthRepository_BlacklistJTI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockAuthRepository_BlacklistJTI_Call) Return(_a0 error) *MockAuthRepository_BlacklistJTI_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthRepository_BlacklistJTI_Call) RunAndReturn(run func(context.Context, string, time.Duration) error) *MockAuthRepository_BlacklistJTI_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOTP provides a mock function with given fields: ctx, purpose, userID
func (_m *MockAuthRepository) DeleteOTP(ctx context.Context, purpose string, userID string) error {
	ret := _m.Called(ctx, purpose, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, purpose, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthRepository_DeleteOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOTP'
type MockAuthRepository_DeleteOTP_Call struct {
	*mock.Call
}

// DeleteOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - purpose string
//   - userID string
func (_e *MockAuthRepository_Expecter) DeleteOTP(ctx interface{}, purpose interface{}, userID interface{}) *MockAuthRepository_DeleteOTP_Call {
	return &MockAuthRepository_DeleteOTP_Call{Call: _e.mock.On("DeleteOTP", ctx, purpose, userID)}
}

func (_c *MockAuthRepository_DeleteOTP_Call) Run(run func(ctx context.Context, purpose string, userID string)) *MockAuthRepository_DeleteOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthRepository_DeleteOTP_Call) Return(_a0 error) *MockAuthRepository_DeleteOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthRepository_DeleteOTP_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAuthRepository_DeleteOTP_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshToken provides a mock function with given fields: ctx, token
func (_m *MockAuthRepository) DeleteRefreshToken(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthRepository_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type MockAuthRepository_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthRepository_Expecter) DeleteRefreshToken(ctx interface{}, token interface{}) *MockAuthRepository_DeleteRefreshToken_Call {
	return &MockAuthRepository_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", ctx, token)}
}

func (_c *MockAuthRepository_DeleteRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockAuthRepository_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthRepository_DeleteRefreshToken_Call) Return(_a0 error) *MockAuthRepository_DeleteRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthRepository_DeleteRefreshToken_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthRepository_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetOTP provides a mock function with given fields: ctx, purpose, userID
func (_m *MockAuthRepository) GetOTP(ctx context.Context, purpose string, userID string) (string, error) {
	ret := _m.Called(ctx, purpose, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOTP")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, purpose, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, purpose, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, purpose, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthRepository_GetOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOTP'
type MockAuthRepository_GetOTP_Call struct {
	*mock.Call
}

// GetOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - purpose string
//   - userID string
func (_e *MockAuthRepository_Expecter) GetOTP(ctx interface{}, purpose interface{}, userID interface{}) *MockAuthRepository_GetOTP_Call {
	return &MockAuthRepository_GetOTP_Call{Call: _e.mock.On("GetOTP", ctx, purpose, userID)}
}

func (_c *MockAuthRepository_GetOTP_Call) Run(run func(ctx context.Context, purpose string, userID string)) *MockAuthRepository_GetOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthRepository_GetOTP_Call) Return(_a0 string, _a1 error) *MockAuthRepository_GetOTP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthRepository_GetOTP_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockAuthRepository_GetOTP_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshToken provides a mock function with given fields: ctx, token
func (_m *MockAuthRepository) GetRefreshToken(ctx context.Context, token string) (string, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthRepository_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type MockAuthRepository_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthRepository_Expecter) GetRefreshToken(ctx interface{}, token interface{}) *MockAuthRepository_GetRefreshToken_Call {
	return &MockAuthRepository_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", ctx, token)}
}

func (_c *MockAuthRepository_GetRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockAuthRepository_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthRepository_GetRefreshToken_Call) Return(_a0 string, _a1 error) *MockAuthRepository_GetRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthRepository_GetRefreshToken_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockAuthRepository_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// IncrLoginFail provides a mock function with given fields: ctx, email, ip, ttl
func (_m *MockAuthRepository) IncrLoginFail(ctx context.Context, email string, ip string, ttl time.Duration) (int64, error) {
	ret := _m.Called(ctx, email, ip, ttl)

	if len(ret) == 0 {
		panic("no return value specified for IncrLoginFail")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (int64, error)); ok {
		return rf(ctx, email, ip, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) int64); ok {
		r0 = rf(ctx, email, ip, ttl)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = rf(ctx, email, ip, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthRepository_IncrLoginFail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrLoginFail'
type MockAuthRepository_IncrLoginFail_Call struct {
	*mock.Call
}

// IncrLoginFail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - ip string
//   - ttl time.Duration
func (_e *MockAuthRepository_Expecter) IncrLoginFail(ctx interface{}, email interface{}, ip interface{}, ttl interface{}) *MockAuthRepository_IncrLoginFail_Call {
	return &MockAuthRepository_IncrLoginFail_Call{Call: _e.mock.On("IncrLoginFail", ctx, email, ip, ttl)}
}

func (_c *MockAuthRepository_IncrLoginFail_Call) Run(run func(ctx context.Context, email string, ip string, ttl time.Duration)) *MockAuthRepository_IncrLoginFail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockAuthRepository_IncrLoginFail_Call) Return(_a0 int64, _a1 error) *MockAuthRepository_IncrLoginFail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthRepository_IncrLoginFail_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) (int64, error)) *MockAuthRepository_IncrLoginFail_Call {
	_c.Call.Return(run)
	return _c
}

// IncrOTPFail provides a mock function with given fields: ctx, purpose, userID, ttl
func (_m *MockAuthRepository) IncrOTPFail(ctx context.Context, purpose string, userID string, ttl time.Duration) (int64, error) {
	ret := _m.Called(ctx, purpose, userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for IncrOTPFail")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (int64, error)); ok {
		return rf(ctx, purpose, userID, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) int64); ok {
		r0 = rf(ctx, purpose, userID, ttl)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = rf(ctx, purpose, userID, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthRepository_IncrOTPFail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrOTPFail'
type MockAuthRepository_IncrOTPFail_Call struct {
	*mock.Call
}

// IncrOTPFail is a helper method to define mock.On call
//   - ctx context.Context
//   - purpose string
//   - userID string
//   - ttl time.Duration
func (_e *MockAuthRepository_Expecter) IncrOTPFail(ctx interface{}, purpose interface{}, userID interface{}, ttl interface{}) *MockAuthRepository_IncrOTPFail_Call {
	return &MockAuthRepository_IncrOTPFail_Call{Call: _e.mock.On("IncrOTPFail", ctx, purpose, userID, ttl)}
}

func (_c *MockAuthRepository_IncrOTPFail_Call) Run(run func(ctx context.Context, purpose string, userID string, ttl time.Duration)) *MockAuthRepository_IncrOTPFail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockAuthRepository_IncrOTPFail_Call) Return(_a0 int64, _a1 error) *MockAuthRepository_IncrOTPFail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthRepository_IncrOTPFail_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) (int64, error)) *MockAuthRepository_IncrOTPFail_Call {
	_c.Call.Return(run)
	return _c
}

// IncrResend provides a mock function with given fields: ctx, email
func (_m *MockAuthRepository) IncrResend(ctx context.Context, email string) (int64, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for IncrResend")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthRepository_IncrResend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrResend'
type MockAuthRepository_IncrResend_Call struct {
	*mock.Call
}

// IncrResend is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthRepository_Expecter) IncrResend(ctx interface{}, email interface{}) *MockAuthRepository_IncrResend_Call {
	return &MockAuthRepository_IncrResend_Call{Call: _e.mock.On("IncrResend", ctx, email)}
}

func (_c *MockAuthRepository_IncrResend_Call) Run(run func(ctx context.Context, email string)) *MockAuthRepository_IncrResend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthRepository_IncrResend_Call) Return(_a0 int64, _a1 error) *MockAuthRepository_IncrResend_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthRepository_IncrResend_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockAuthRepository_IncrResend_Call {
	_c.Call.Return(run)
	return _c
}

// IsJTIBlacklisted provides a mock function with given fields: ctx, jti
func (_m *MockAuthRepository) IsJTIBlacklisted(ctx context.Context, jti string) (bool, error) {
	ret := _m.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for IsJTIBlacklisted")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, jti)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, jti)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jti)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthRepository_IsJTIBlacklisted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsJTIBlacklisted'
type MockAuthRepository_IsJTIBlacklisted_Call struct {
	*mock.Call
}

// IsJTIBlacklisted is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
func (_e *MockAuthRepository_Expecter) IsJTIBlacklisted(ctx interface{}, jti interface{}) *MockAuthRepository_IsJTIBlacklisted_Call {
	return &MockAuthRepository_IsJTIBlacklisted_Call{Call: _e.mock.On("IsJTIBlacklisted", ctx, jti)}
}

func (_c *MockAuthRepository_IsJTIBlacklisted_Call) Run(run func(ctx context.Context, jti string)) *MockAuthRepository_IsJTIBlacklisted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthRepository_IsJTIBlacklisted_Call) Return(_a0 bool, _a1 error) *MockAuthRepository_IsJTIBlacklisted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthRepository_IsJTIBlacklisted_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockAuthRepository_IsJTIBlacklisted_Call {
	_c.Call.Return(run)
	return _c
}

// IsLoginBlocked provides a mock function with given fields: ctx, email, ip
func (_m *MockAuthRepository) IsLoginBlocked(ctx context.Context, email string, ip string) (bool, error) {
	ret := _m.Called(ctx, email, ip)

	if len(ret) == 0 {
		panic("no return value specified for IsLoginBlocked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, email, ip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, email, ip)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthRepository_IsLoginBlocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsLoginBlocked'
type MockAuthRepository_IsLoginBlocked_Call struct {
	*mock.Call
}

// IsLoginBlocked is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - ip string
func (_e *MockAuthRepository_Expecter) IsLoginBlocked(ctx interface{}, email interface{}, ip interface{}) *MockAuthRepository_IsLoginBlocked_Call {
	return &MockAuthRepository_IsLoginBlocked_Call{Call: _e.mock.On("IsLoginBlocked", ctx, email, ip)}
}

func (_c *MockAuthRepository_IsLoginBlocked_Call) Run(run func(ctx context.Context, email string, ip string)) *MockAuthRepository_IsLoginBlocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthRepository_IsLoginBlocked_Call) Return(_a0 bool, _a1 error) *MockAuthRepository_IsLoginBlocked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthRepository_IsLoginBlocked_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockAuthRepository_IsLoginBlocked_Call {
	_c.Call.Return(run)
	return _c
}

// PutOTP provides a mock function with given fields: ctx, purpose, userID, otp, ttl
func (_m *MockAuthRepository) PutOTP(ctx context.Context, purpose string, userID string, otp string, ttl time.Duration) error {
	ret := _m.Called(ctx, purpose, userID, otp, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PutOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Duration) error); ok {
		r0 = rf(ctx, purpose, userID, otp, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthRepository_PutOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutOTP'
type MockAuthRepository_PutOTP_Call struct {
	*mock.Call
}

// PutOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - purpose string
//   - userID string
//   - otp string
//   - ttl time.Duration
func (_e *MockAuthRepository_Expecter) PutOTP(ctx interface{}, purpose interface{}, userID interface{}, otp interface{}, ttl interface{}) *MockAuthRepository_PutOTP_Call {
	return &MockAuthRepository_PutOTP_Call{Call: _e.mock.On("PutOTP", ctx, purpose, userID, otp, ttl)}
}

func (_c *MockAuthRepository_PutOTP_Call) Run(run func(ctx context.Context, purpose string, userID string, otp string, ttl time.Duration)) *MockAuthRepository_PutOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(time.Duration))
	})
	return _c
}

func (_c *MockAuthRepository_PutOTP_Call) Return(_a0 error) *MockAuthRepository_PutOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthRepository_PutOTP_Call) RunAndReturn(run func(context.Context, string, string, string, time.Duration) error) *MockAuthRepository_PutOTP_Call {
	_c.Call.Return(run)
	return _c
}

// PutRefreshToken provides a mock function with given fields: ctx, token, userID, ttl
func (_m *MockAuthRepository) PutRefreshToken(ctx context.Context, token string, userID string, ttl time.Duration) error {
	ret := _m.Called(ctx, token, userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PutRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, token, userID, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthRepository_PutRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutRefreshToken'
type MockAuthRepository_PutRefreshToken_Call struct {
	*mock.Call
}

// PutRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - userID string
//   - ttl time.Duration
func (_e *MockAuthRepository_Expecter) PutRefreshToken(ctx interface{}, token interface{}, userID interface{}, ttl interface{}) *MockAuthRepository_PutRefreshToken_Call {
	return &MockAuthRepository_PutRefreshToken_Call{Call: _e.mock.On("PutRefreshToken", ctx, token, userID, ttl)}
}

func (_c *MockAuthRepository_PutRefreshToken_Call) Run(run func(ctx context.Context, token string, userID string, ttl time.Duration)) *MockAuthRepository_PutRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockAuthRepository_PutRefreshToken_Call) Return(_a0 error) *MockAuthRepository_PutRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthRepository_PutRefreshToken_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) error) *MockAuthRepository_PutRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthRepository creates a new instance of MockAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepository {
	mock := &MockAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
