// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockProductVariantRepository is an autogenerated mock type for the ProductVariantRepository type
type MockProductVariantRepository struct {
	mock.Mock
}

type MockProductVariantRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductVariantRepository) EXPECT() *MockProductVariantRepository_Expecter {
	return &MockProductVariantRepository_Expecter{mock: &_m.Mock}
}

// AdjustStock provides a mock function with given fields: ctx, variantID, delta
func (_m *MockProductVariantRepository) AdjustStock(ctx context.Context, variantID uuid.UUID, delta int) (int, error) {
	ret := _m.Called(ctx, variantID, delta)

	if len(ret) == 0 {
		panic("no return value specified for AdjustStock")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (int, error)); ok {
		return rf(ctx, variantID, delta)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) int); ok {
		r0 = rf(ctx, variantID, delta)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, variantID, delta)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductVariantRepository_AdjustStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdjustStock'
type MockProductVariantRepository_AdjustStock_Call struct {
	*mock.Call
}

// AdjustStock is a helper method to define mock.On call
//   - ctx context.Context
//   - variantID uuid.UUID
//   - delta int
func (_e *MockProductVariantRepository_Expecter) AdjustStock(ctx interface{}, variantID interface{}, delta interface{}) *MockProductVariantRepository_AdjustStock_Call {
	return &MockProductVariantRepository_AdjustStock_Call{Call: _e.mock.On("AdjustStock", ctx, variantID, delta)}
}

func (_c *MockProductVariantRepository_AdjustStock_Call) Run(run func(ctx context.Context, variantID uuid.UUID, delta int)) *MockProductVariantRepository_AdjustStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockProductVariantRepository_AdjustStock_Call) Return(_a0 int, _a1 error) *MockProductVariantRepository_AdjustStock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductVariantRepository_AdjustStock_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) (int, error)) *MockProductVariantRepository_AdjustStock_Call {
	_c.Call.Return(run)
	return _c
}

// AdjustStockWithMovement provides a mock function with given fields: ctx, variantID, delta, m
func (_m *MockProductVariantRepository) AdjustStockWithMovement(ctx context.Context, variantID uuid.UUID, delta int, m *entity.StockMovement) (int, error) {
	ret := _m.Called(ctx, variantID, delta, m)

	if len(ret) == 0 {
		panic("no return value specified for AdjustStockWithMovement")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, *entity.StockMovement) (int, error)); ok {
		return rf(ctx, variantID, delta, m)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, *entity.StockMovement) int); ok {
		r0 = rf(ctx, variantID, delta, m)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, *entity.StockMovement) error); ok {
		r1 = rf(ctx, variantID, delta, m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductVariantRepository_AdjustStockWithMovement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdjustStockWithMovement'
type MockProductVariantRepository_AdjustStockWithMovement_Call struct {
	*mock.Call
}

// AdjustStockWithMovement is a helper method to define mock.On call
//   - ctx context.Context
//   - variantID uuid.UUID
//   - delta int
//   - m *entity.StockMovement
func (_e *MockProductVariantRepository_Expecter) AdjustStockWithMovement(ctx interface{}, variantID interface{}, delta interface{}, m interface{}) *MockProductVariantRepository_AdjustStockWithMovement_Call {
	return &MockProductVariantRepository_AdjustStockWithMovement_Call{Call: _e.mock.On("AdjustStockWithMovement", ctx, variantID, delta, m)}
}

func (_c *MockProductVariantRepository_AdjustStockWithMovement_Call) Run(run func(ctx context.Context, variantID uuid.UUID, delta int, m *entity.StockMovement)) *MockProductVariantRepository_AdjustStockWithMovement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(*entity.StockMovement))
	})
	return _c
}

func (_c *MockProductVariantRepository_AdjustStockWithMovement_Call) Return(_a0 int, _a1 error) *MockProductVariantRepository_AdjustStockWithMovement_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductVariantRepository_AdjustStockWithMovement_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, *entity.StockMovement) (int, error)) *MockProductVariantRepository_AdjustStockWithMovement_Call {
	_c.Call.Return(run)
	return _c
}

// CountActiveByProductID provides a mock function with given fields: ctx, productID
func (_m *MockProductVariantRepository) CountActiveByProductID(ctx context.Context, productID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveByProductID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductVariantRepository_CountActiveByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountActiveByProductID'
type MockProductVariantRepository_CountActiveByProductID_Call struct {
	*mock.Call
}

// CountActiveByProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockProductVariantRepository_Expecter) CountActiveByProductID(ctx interface{}, productID interface{}) *MockProductVariantRepository_CountActiveByProductID_Call {
	return &MockProductVariantRepository_CountActiveByProductID_Call{Call: _e.mock.On("CountActiveByProductID", ctx, productID)}
}

func (_c *MockProductVariantRepository_CountActiveByProductID_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockProductVariantRepository_CountActiveByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductVariantRepository_CountActiveByProductID_Call) Return(_a0 int, _a1 error) *MockProductVariantRepository_CountActiveByProductID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductVariantRepository_CountActiveByProductID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockProductVariantRepository_CountActiveByProductID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, v
func (_m *MockProductVariantRepository) Create(ctx context.Context, v *entity.ProductVariant) error {
	ret := _m.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ProductVariant) error); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductVariantRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductVariantRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - v *entity.ProductVariant
func (_e *MockProductVariantRepository_Expecter) Create(ctx interface{}, v interface{}) *MockProductVariantRepository_Create_Call {
	return &MockProductVariantRepository_Create_Call{Call: _e.mock.On("Create", ctx, v)}
}

func (_c *MockProductVariantRepository_Create_Call) Run(run func(ctx context.Context, v *entity.ProductVariant)) *MockProductVariantRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.ProductVariant))
	})
	return _c
}

func (_c *MockProductVariantRepository_Create_Call) Return(_a0 error) *MockProductVariantRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductVariantRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.ProductVariant) error) *MockProductVariantRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockProductVariantRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.ProductVariant, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.ProductVariant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.ProductVariant, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.ProductVariant); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ProductVariant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductVariantRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockProductVariantRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProductVariantRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockProductVariantRepository_FindByID_Call {
	return &MockProductVariantRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockProductVariantRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProductVariantRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductVariantRepository_FindByID_Call) Return(_a0 *entity.ProductVariant, _a1 error) *MockProductVariantRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductVariantRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.ProductVariant, error)) *MockProductVariantRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDAndSupplier provides a mock function with given fields: ctx, id, supplierID
func (_m *MockProductVariantRepository) FindByIDAndSupplier(ctx context.Context, id uuid.UUID, supplierID uuid.UUID) (*entity.ProductVariant, error) {
	ret := _m.Called(ctx, id, supplierID)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDAndSupplier")
	}

	var r0 *entity.ProductVariant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.ProductVariant, error)); ok {
		return rf(ctx, id, supplierID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.ProductVariant); ok {
		r0 = rf(ctx, id, supplierID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ProductVariant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, supplierID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductVariantRepository_FindByIDAndSupplier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDAndSupplier'
type MockProductVariantRepository_FindByIDAndSupplier_Call struct {
	*mock.Call
}

// FindByIDAndSupplier is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - supplierID uuid.UUID
func (_e *MockProductVariantRepository_Expecter) FindByIDAndSupplier(ctx interface{}, id interface{}, supplierID interface{}) *MockProductVariantRepository_FindByIDAndSupplier_Call {
	return &MockProductVariantRepository_FindByIDAndSupplier_Call{Call: _e.mock.On("FindByIDAndSupplier", ctx, id, supplierID)}
}

func (_c *MockProductVariantRepository_FindByIDAndSupplier_Call) Run(run func(ctx context.Context, id uuid.UUID, supplierID uuid.UUID)) *MockProductVariantRepository_FindByIDAndSupplier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductVariantRepository_FindByIDAndSupplier_Call) Return(_a0 *entity.ProductVariant, _a1 error) *MockProductVariantRepository_FindByIDAndSupplier_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductVariantRepository_FindByIDAndSupplier_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*entity.ProductVariant, error)) *MockProductVariantRepository_FindByIDAndSupplier_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function with given fields: ctx, ids
func (_m *MockProductVariantRepository) FindByIDs(ctx context.Context, ids []uuid.UUID) ([]*entity.ProductVariant, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []*entity.ProductVariant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]*entity.ProductVariant, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []*entity.ProductVariant); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ProductVariant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductVariantRepository_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type MockProductVariantRepository_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockProductVariantRepository_Expecter) FindByIDs(ctx interface{}, ids interface{}) *MockProductVariantRepository_FindByIDs_Call {
	return &MockProductVariantRepository_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, ids)}
}

func (_c *MockProductVariantRepository_FindByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockProductVariantRepository_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockProductVariantRepository_FindByIDs_Call) Return(_a0 []*entity.ProductVariant, _a1 error) *MockProductVariantRepository_FindByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductVariantRepository_FindByIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]*entity.ProductVariant, error)) *MockProductVariantRepository_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ListBelowThreshold provides a mock function with given fields: ctx, threshold
func (_m *MockProductVariantRepository) ListBelowThreshold(ctx context.Context, threshold int) ([]*entity.ProductVariant, error) {
	ret := _m.Called(ctx, threshold)

	if len(ret) == 0 {
		panic("no return value specified for ListBelowThreshold")
	}

	var r0 []*entity.ProductVariant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*entity.ProductVariant, error)); ok {
		return rf(ctx, threshold)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*entity.ProductVariant); ok {
		r0 = rf(ctx, threshold)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ProductVariant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, threshold)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductVariantRepository_ListBelowThreshold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBelowThreshold'
type MockProductVariantRepository_ListBelowThreshold_Call struct {
	*mock.Call
}

// ListBelowThreshold is a helper method to define mock.On call
//   - ctx context.Context
//   - threshold int
func (_e *MockProductVariantRepository_Expecter) ListBelowThreshold(ctx interface{}, threshold interface{}) *MockProductVariantRepository_ListBelowThreshold_Call {
	return &MockProductVariantRepository_ListBelowThreshold_Call{Call: _e.mock.On("ListBelowThreshold", ctx, threshold)}
}

func (_c *MockProductVariantRepository_ListBelowThreshold_Call) Run(run func(ctx context.Context, threshold int)) *MockProductVariantRepository_ListBelowThreshold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockProductVariantRepository_ListBelowThreshold_Call) Return(_a0 []*entity.ProductVariant, _a1 error) *MockProductVariantRepository_ListBelowThreshold_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductVariantRepository_ListBelowThreshold_Call) RunAndReturn(run func(context.Context, int) ([]*entity.ProductVariant, error)) *MockProductVariantRepository_ListBelowThreshold_Call {
	_c.Call.Return(run)
	return _c
}

// ListByProductID provides a mock function with given fields: ctx, productID
func (_m *MockProductVariantRepository) ListByProductID(ctx context.Context, productID uuid.UUID) ([]*entity.ProductVariant, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for ListByProductID")
	}

	var r0 []*entity.ProductVariant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.ProductVariant, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.ProductVariant); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ProductVariant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductVariantRepository_ListByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByProductID'
type MockProductVariantRepository_ListByProductID_Call struct {
	*mock.Call
}

// ListByProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockProductVariantRepository_Expecter) ListByProductID(ctx interface{}, productID interface{}) *MockProductVariantRepository_ListByProductID_Call {
	return &MockProductVariantRepository_ListByProductID_Call{Call: _e.mock.On("ListByProductID", ctx, productID)}
}

func (_c *MockProductVariantRepository_ListByProductID_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockProductVariantRepository_ListByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductVariantRepository_ListByProductID_Call) Return(_a0 []*entity.ProductVariant, _a1 error) *MockProductVariantRepository_ListByProductID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductVariantRepository_ListByProductID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.ProductVariant, error)) *MockProductVariantRepository_ListByProductID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, v
func (_m *MockProductVariantRepository) Update(ctx context.Context, v *entity.ProductVariant) error {
	ret := _m.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ProductVariant) error); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductVariantRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductVariantRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - v *entity.ProductVariant
func (_e *MockProductVariantRepository_Expecter) Update(ctx interface{}, v interface{}) *MockProductVariantRepository_Update_Call {
	return &MockProductVariantRepository_Update_Call{Call: _e.mock.On("Update", ctx, v)}
}

func (_c *MockProductVariantRepository_Update_Call) Run(run func(ctx context.Context, v *entity.ProductVariant)) *MockProductVariantRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.ProductVariant))
	})
	return _c
}

func (_c *MockProductVariantRepository_Update_Call) Return(_a0 error) *MockProductVariantRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductVariantRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.ProductVariant) error) *MockProductVariantRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductVariantRepository creates a new instance of MockProductVariantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductVariantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductVariantRepository {
	mock := &MockProductVariantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
