// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCheckoutGroupRepository is an autogenerated mock type for the CheckoutGroupRepository type
type MockCheckoutGroupRepository struct {
	mock.Mock
}

type MockCheckoutGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckoutGroupRepository) EXPECT() *MockCheckoutGroupRepository_Expecter {
	return &MockCheckoutGroupRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, g
func (_m *MockCheckoutGroupRepository) Create(ctx context.Context, g *entity.CheckoutGroup) error {
	ret := _m.Called(ctx, g)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.CheckoutGroup) error); ok {
		r0 = rf(ctx, g)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCheckoutGroupRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCheckoutGroupRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - g *entity.CheckoutGroup
func (_e *MockCheckoutGroupRepository_Expecter) Create(ctx interface{}, g interface{}) *MockCheckoutGroupRepository_Create_Call {
	return &MockCheckoutGroupRepository_Create_Call{Call: _e.mock.On("Create", ctx, g)}
}

func (_c *MockCheckoutGroupRepository_Create_Call) Run(run func(ctx context.Context, g *entity.CheckoutGroup)) *MockCheckoutGroupRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.CheckoutGroup))
	})
	return _c
}

func (_c *MockCheckoutGroupRepository_Create_Call) Return(_a0 error) *MockCheckoutGroupRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCheckoutGroupRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.CheckoutGroup) error) *MockCheckoutGroupRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockCheckoutGroupRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.CheckoutGroup, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.CheckoutGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.CheckoutGroup, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.CheckoutGroup); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CheckoutGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCheckoutGroupRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCheckoutGroupRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCheckoutGroupRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockCheckoutGroupRepository_FindByID_Call {
	return &MockCheckoutGroupRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCheckoutGroupRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCheckoutGroupRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCheckoutGroupRepository_FindByID_Call) Return(_a0 *entity.CheckoutGroup, _a1 error) *MockCheckoutGroupRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCheckoutGroupRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.CheckoutGroup, error)) *MockCheckoutGroupRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockCheckoutGroupRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status string) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCheckoutGroupRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockCheckoutGroupRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status string
func (_e *MockCheckoutGroupRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockCheckoutGroupRepository_UpdateStatus_Call {
	return &MockCheckoutGroupRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockCheckoutGroupRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status string)) *MockCheckoutGroupRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockCheckoutGroupRepository_UpdateStatus_Call) Return(_a0 error) *MockCheckoutGroupRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCheckoutGroupRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockCheckoutGroupRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCheckoutGroupRepository creates a new instance of MockCheckoutGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckoutGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckoutGroupRepository {
	mock := &MockCheckoutGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
