// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSupplierBankAccountRepository is an autogenerated mock type for the SupplierBankAccountRepository type
type MockSupplierBankAccountRepository struct {
	mock.Mock
}

type MockSupplierBankAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSupplierBankAccountRepository) EXPECT() *MockSupplierBankAccountRepository_Expecter {
	return &MockSupplierBankAccountRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, a
func (_m *MockSupplierBankAccountRepository) Create(ctx context.Context, a *entity.SupplierBankAccount) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SupplierBankAccount) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupplierBankAccountRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSupplierBankAccountRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - a *entity.SupplierBankAccount
func (_e *MockSupplierBankAccountRepository_Expecter) Create(ctx interface{}, a interface{}) *MockSupplierBankAccountRepository_Create_Call {
	return &MockSupplierBankAccountRepository_Create_Call{Call: _e.mock.On("Create", ctx, a)}
}

func (_c *MockSupplierBankAccountRepository_Create_Call) Run(run func(ctx context.Context, a *entity.SupplierBankAccount)) *MockSupplierBankAccountRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.SupplierBankAccount))
	})
	return _c
}

func (_c *MockSupplierBankAccountRepository_Create_Call) Return(_a0 error) *MockSupplierBankAccountRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupplierBankAccountRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.SupplierBankAccount) error) *MockSupplierBankAccountRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockSupplierBankAccountRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupplierBankAccountRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSupplierBankAccountRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSupplierBankAccountRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockSupplierBankAccountRepository_Delete_Call {
	return &MockSupplierBankAccountRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSupplierBankAccountRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSupplierBankAccountRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSupplierBankAccountRepository_Delete_Call) Return(_a0 error) *MockSupplierBankAccountRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupplierBankAccountRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockSupplierBankAccountRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockSupplierBankAccountRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.SupplierBankAccount, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.SupplierBankAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.SupplierBankAccount, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.SupplierBankAccount); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SupplierBankAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplierBankAccountRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockSupplierBankAccountRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSupplierBankAccountRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockSupplierBankAccountRepository_FindByID_Call {
	return &MockSupplierBankAccountRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockSupplierBankAccountRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSupplierBankAccountRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSupplierBankAccountRepository_FindByID_Call) Return(_a0 *entity.SupplierBankAccount, _a1 error) *MockSupplierBankAccountRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupplierBankAccountRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.SupplierBankAccount, error)) *MockSupplierBankAccountRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySupplierID provides a mock function with given fields: ctx, supplierID
func (_m *MockSupplierBankAccountRepository) FindBySupplierID(ctx context.Context, supplierID uuid.UUID) ([]*entity.SupplierBankAccount, error) {
	ret := _m.Called(ctx, supplierID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySupplierID")
	}

	var r0 []*entity.SupplierBankAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.SupplierBankAccount, error)); ok {
		return rf(ctx, supplierID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.SupplierBankAccount); ok {
		r0 = rf(ctx, supplierID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.SupplierBankAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, supplierID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplierBankAccountRepository_FindBySupplierID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySupplierID'
type MockSupplierBankAccountRepository_FindBySupplierID_Call struct {
	*mock.Call
}

// FindBySupplierID is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID uuid.UUID
func (_e *MockSupplierBankAccountRepository_Expecter) FindBySupplierID(ctx interface{}, supplierID interface{}) *MockSupplierBankAccountRepository_FindBySupplierID_Call {
	return &MockSupplierBankAccountRepository_FindBySupplierID_Call{Call: _e.mock.On("FindBySupplierID", ctx, supplierID)}
}

func (_c *MockSupplierBankAccountRepository_FindBySupplierID_Call) Run(run func(ctx context.Context, supplierID uuid.UUID)) *MockSupplierBankAccountRepository_FindBySupplierID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSupplierBankAccountRepository_FindBySupplierID_Call) Return(_a0 []*entity.SupplierBankAccount, _a1 error) *MockSupplierBankAccountRepository_FindBySupplierID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupplierBankAccountRepository_FindBySupplierID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.SupplierBankAccount, error)) *MockSupplierBankAccountRepository_FindBySupplierID_Call {
	_c.Call.Return(run)
	return _c
}

// UnsetDefault provides a mock function with given fields: ctx, supplierID
func (_m *MockSupplierBankAccountRepository) UnsetDefault(ctx context.Context, supplierID uuid.UUID) error {
	ret := _m.Called(ctx, supplierID)

	if len(ret) == 0 {
		panic("no return value specified for UnsetDefault")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, supplierID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupplierBankAccountRepository_UnsetDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsetDefault'
type MockSupplierBankAccountRepository_UnsetDefault_Call struct {
	*mock.Call
}

// UnsetDefault is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID uuid.UUID
func (_e *MockSupplierBankAccountRepository_Expecter) UnsetDefault(ctx interface{}, supplierID interface{}) *MockSupplierBankAccountRepository_UnsetDefault_Call {
	return &MockSupplierBankAccountRepository_UnsetDefault_Call{Call: _e.mock.On("UnsetDefault", ctx, supplierID)}
}

func (_c *MockSupplierBankAccountRepository_UnsetDefault_Call) Run(run func(ctx context.Context, supplierID uuid.UUID)) *MockSupplierBankAccountRepository_UnsetDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSupplierBankAccountRepository_UnsetDefault_Call) Return(_a0 error) *MockSupplierBankAccountRepository_UnsetDefault_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupplierBankAccountRepository_UnsetDefault_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockSupplierBankAccountRepository_UnsetDefault_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, a
func (_m *MockSupplierBankAccountRepository) Update(ctx context.Context, a *entity.SupplierBankAccount) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SupplierBankAccount) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupplierBankAccountRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSupplierBankAccountRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - a *entity.SupplierBankAccount
func (_e *MockSupplierBankAccountRepository_Expecter) Update(ctx interface{}, a interface{}) *MockSupplierBankAccountRepository_Update_Call {
	return &MockSupplierBankAccountRepository_Update_Call{Call: _e.mock.On("Update", ctx, a)}
}

func (_c *MockSupplierBankAccountRepository_Update_Call) Run(run func(ctx context.Context, a *entity.SupplierBankAccount)) *MockSupplierBankAccountRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.SupplierBankAccount))
	})
	return _c
}

func (_c *MockSupplierBankAccountRepository_Update_Call) Return(_a0 error) *MockSupplierBankAccountRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupplierBankAccountRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.SupplierBankAccount) error) *MockSupplierBankAccountRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSupplierBankAccountRepository creates a new instance of MockSupplierBankAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSupplierBankAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSupplierBankAccountRepository {
	mock := &MockSupplierBankAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
