// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSupplierBalanceRepository is an autogenerated mock type for the SupplierBalanceRepository type
type MockSupplierBalanceRepository struct {
	mock.Mock
}

type MockSupplierBalanceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSupplierBalanceRepository) EXPECT() *MockSupplierBalanceRepository_Expecter {
	return &MockSupplierBalanceRepository_Expecter{mock: &_m.Mock}
}

// FindBySupplierID provides a mock function with given fields: ctx, supplierID
func (_m *MockSupplierBalanceRepository) FindBySupplierID(ctx context.Context, supplierID uuid.UUID) (*entity.SupplierBalance, error) {
	ret := _m.Called(ctx, supplierID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySupplierID")
	}

	var r0 *entity.SupplierBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.SupplierBalance, error)); ok {
		return rf(ctx, supplierID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.SupplierBalance); ok {
		r0 = rf(ctx, supplierID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SupplierBalance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, supplierID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplierBalanceRepository_FindBySupplierID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySupplierID'
type MockSupplierBalanceRepository_FindBySupplierID_Call struct {
	*mock.Call
}

// FindBySupplierID is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID uuid.UUID
func (_e *MockSupplierBalanceRepository_Expecter) FindBySupplierID(ctx interface{}, supplierID interface{}) *MockSupplierBalanceRepository_FindBySupplierID_Call {
	return &MockSupplierBalanceRepository_FindBySupplierID_Call{Call: _e.mock.On("FindBySupplierID", ctx, supplierID)}
}

func (_c *MockSupplierBalanceRepository_FindBySupplierID_Call) Run(run func(ctx context.Context, supplierID uuid.UUID)) *MockSupplierBalanceRepository_FindBySupplierID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSupplierBalanceRepository_FindBySupplierID_Call) Return(_a0 *entity.SupplierBalance, _a1 error) *MockSupplierBalanceRepository_FindBySupplierID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupplierBalanceRepository_FindBySupplierID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.SupplierBalance, error)) *MockSupplierBalanceRepository_FindBySupplierID_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function with given fields: ctx, supplierID, delta
func (_m *MockSupplierBalanceRepository) Increment(ctx context.Context, supplierID uuid.UUID, delta float64) (float64, error) {
	ret := _m.Called(ctx, supplierID, delta)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64) (float64, error)); ok {
		return rf(ctx, supplierID, delta)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64) float64); ok {
		r0 = rf(ctx, supplierID, delta)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, float64) error); ok {
		r1 = rf(ctx, supplierID, delta)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplierBalanceRepository_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type MockSupplierBalanceRepository_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID uuid.UUID
//   - delta float64
func (_e *MockSupplierBalanceRepository_Expecter) Increment(ctx interface{}, supplierID interface{}, delta interface{}) *MockSupplierBalanceRepository_Increment_Call {
	return &MockSupplierBalanceRepository_Increment_Call{Call: _e.mock.On("Increment", ctx, supplierID, delta)}
}

func (_c *MockSupplierBalanceRepository_Increment_Call) Run(run func(ctx context.Context, supplierID uuid.UUID, delta float64)) *MockSupplierBalanceRepository_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(float64))
	})
	return _c
}

func (_c *MockSupplierBalanceRepository_Increment_Call) Return(newBalance float64, err error) *MockSupplierBalanceRepository_Increment_Call {
	_c.Call.Return(newBalance, err)
	return _c
}

func (_c *MockSupplierBalanceRepository_Increment_Call) RunAndReturn(run func(context.Context, uuid.UUID, float64) (float64, error)) *MockSupplierBalanceRepository_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSupplierBalanceRepository creates a new instance of MockSupplierBalanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSupplierBalanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSupplierBalanceRepository {
	mock := &MockSupplierBalanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
