// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockStockMovementRepository is an autogenerated mock type for the StockMovementRepository type
type MockStockMovementRepository struct {
	mock.Mock
}

type MockStockMovementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStockMovementRepository) EXPECT() *MockStockMovementRepository_Expecter {
	return &MockStockMovementRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, m
func (_m *MockStockMovementRepository) Create(ctx context.Context, m *entity.StockMovement) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.StockMovement) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockMovementRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStockMovementRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - m *entity.StockMovement
func (_e *MockStockMovementRepository_Expecter) Create(ctx interface{}, m interface{}) *MockStockMovementRepository_Create_Call {
	return &MockStockMovementRepository_Create_Call{Call: _e.mock.On("Create", ctx, m)}
}

func (_c *MockStockMovementRepository_Create_Call) Run(run func(ctx context.Context, m *entity.StockMovement)) *MockStockMovementRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.StockMovement))
	})
	return _c
}

func (_c *MockStockMovementRepository_Create_Call) Return(_a0 error) *MockStockMovementRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockMovementRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.StockMovement) error) *MockStockMovementRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByVariantID provides a mock function with given fields: ctx, variantID, page, perPage
func (_m *MockStockMovementRepository) ListByVariantID(ctx context.Context, variantID uuid.UUID, page int, perPage int) ([]*entity.StockMovement, int, error) {
	ret := _m.Called(ctx, variantID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for ListByVariantID")
	}

	var r0 []*entity.StockMovement
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*entity.StockMovement, int, error)); ok {
		return rf(ctx, variantID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*entity.StockMovement); ok {
		r0 = rf(ctx, variantID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.StockMovement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, variantID, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, variantID, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStockMovementRepository_ListByVariantID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByVariantID'
type MockStockMovementRepository_ListByVariantID_Call struct {
	*mock.Call
}

// ListByVariantID is a helper method to define mock.On call
//   - ctx context.Context
//   - variantID uuid.UUID
//   - page int
//   - perPage int
func (_e *MockStockMovementRepository_Expecter) ListByVariantID(ctx interface{}, variantID interface{}, page interface{}, perPage interface{}) *MockStockMovementRepository_ListByVariantID_Call {
	return &MockStockMovementRepository_ListByVariantID_Call{Call: _e.mock.On("ListByVariantID", ctx, variantID, page, perPage)}
}

func (_c *MockStockMovementRepository_ListByVariantID_Call) Run(run func(ctx context.Context, variantID uuid.UUID, page int, perPage int)) *MockStockMovementRepository_ListByVariantID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockStockMovementRepository_ListByVariantID_Call) Return(_a0 []*entity.StockMovement, _a1 int, _a2 error) *MockStockMovementRepository_ListByVariantID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStockMovementRepository_ListByVariantID_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*entity.StockMovement, int, error)) *MockStockMovementRepository_ListByVariantID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStockMovementRepository creates a new instance of MockStockMovementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStockMovementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStockMovementRepository {
	mock := &MockStockMovementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
