// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockBannerRepository is an autogenerated mock type for the BannerRepository type
type MockBannerRepository struct {
	mock.Mock
}

type MockBannerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBannerRepository) EXPECT() *MockBannerRepository_Expecter {
	return &MockBannerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, b
func (_m *MockBannerRepository) Create(ctx context.Context, b *entity.Banner) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Banner) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBannerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBannerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - b *entity.Banner
func (_e *MockBannerRepository_Expecter) Create(ctx interface{}, b interface{}) *MockBannerRepository_Create_Call {
	return &MockBannerRepository_Create_Call{Call: _e.mock.On("Create", ctx, b)}
}

func (_c *MockBannerRepository_Create_Call) Run(run func(ctx context.Context, b *entity.Banner)) *MockBannerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Banner))
	})
	return _c
}

func (_c *MockBannerRepository_Create_Call) Return(_a0 error) *MockBannerRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBannerRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Banner) error) *MockBannerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockBannerRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBannerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBannerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockBannerRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockBannerRepository_Delete_Call {
	return &MockBannerRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockBannerRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockBannerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockBannerRepository_Delete_Call) Return(_a0 error) *MockBannerRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBannerRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockBannerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockBannerRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Banner, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Banner
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Banner, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Banner); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Banner)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBannerRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBannerRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockBannerRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockBannerRepository_FindByID_Call {
	return &MockBannerRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockBannerRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockBannerRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockBannerRepository_FindByID_Call) Return(_a0 *entity.Banner, _a1 error) *MockBannerRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBannerRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Banner, error)) *MockBannerRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListActive provides a mock function with given fields: ctx
func (_m *MockBannerRepository) ListActive(ctx context.Context) ([]*entity.Banner, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListActive")
	}

	var r0 []*entity.Banner
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Banner, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Banner); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Banner)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBannerRepository_ListActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActive'
type MockBannerRepository_ListActive_Call struct {
	*mock.Call
}

// ListActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBannerRepository_Expecter) ListActive(ctx interface{}) *MockBannerRepository_ListActive_Call {
	return &MockBannerRepository_ListActive_Call{Call: _e.mock.On("ListActive", ctx)}
}

func (_c *MockBannerRepository_ListActive_Call) Run(run func(ctx context.Context)) *MockBannerRepository_ListActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBannerRepository_ListActive_Call) Return(_a0 []*entity.Banner, _a1 error) *MockBannerRepository_ListActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBannerRepository_ListActive_Call) RunAndReturn(run func(context.Context) ([]*entity.Banner, error)) *MockBannerRepository_ListActive_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function with given fields: ctx
func (_m *MockBannerRepository) ListAll(ctx context.Context) ([]*entity.Banner, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []*entity.Banner
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Banner, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Banner); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Banner)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBannerRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockBannerRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBannerRepository_Expecter) ListAll(ctx interface{}) *MockBannerRepository_ListAll_Call {
	return &MockBannerRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockBannerRepository_ListAll_Call) Run(run func(ctx context.Context)) *MockBannerRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBannerRepository_ListAll_Call) Return(_a0 []*entity.Banner, _a1 error) *MockBannerRepository_ListAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBannerRepository_ListAll_Call) RunAndReturn(run func(context.Context) ([]*entity.Banner, error)) *MockBannerRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, b
func (_m *MockBannerRepository) Update(ctx context.Context, b *entity.Banner) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Banner) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBannerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBannerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - b *entity.Banner
func (_e *MockBannerRepository_Expecter) Update(ctx interface{}, b interface{}) *MockBannerRepository_Update_Call {
	return &MockBannerRepository_Update_Call{Call: _e.mock.On("Update", ctx, b)}
}

func (_c *MockBannerRepository_Update_Call) Run(run func(ctx context.Context, b *entity.Banner)) *MockBannerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Banner))
	})
	return _c
}

func (_c *MockBannerRepository_Update_Call) Return(_a0 error) *MockBannerRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBannerRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Banner) error) *MockBannerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBannerRepository creates a new instance of MockBannerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBannerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBannerRepository {
	mock := &MockBannerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
