// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	repository "erdinhrmwn/bangunin/internal/domain/repository"

	uuid "github.com/google/uuid"
)

// MockStockReservationRepository is an autogenerated mock type for the StockReservationRepository type
type MockStockReservationRepository struct {
	mock.Mock
}

type MockStockReservationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStockReservationRepository) EXPECT() *MockStockReservationRepository_Expecter {
	return &MockStockReservationRepository_Expecter{mock: &_m.Mock}
}

// ApplyAdjustments provides a mock function with given fields: ctx, adjustments
func (_m *MockStockReservationRepository) ApplyAdjustments(ctx context.Context, adjustments []repository.ReservationAdjustment) error {
	ret := _m.Called(ctx, adjustments)

	if len(ret) == 0 {
		panic("no return value specified for ApplyAdjustments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []repository.ReservationAdjustment) error); ok {
		r0 = rf(ctx, adjustments)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockReservationRepository_ApplyAdjustments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyAdjustments'
type MockStockReservationRepository_ApplyAdjustments_Call struct {
	*mock.Call
}

// ApplyAdjustments is a helper method to define mock.On call
//   - ctx context.Context
//   - adjustments []repository.ReservationAdjustment
func (_e *MockStockReservationRepository_Expecter) ApplyAdjustments(ctx interface{}, adjustments interface{}) *MockStockReservationRepository_ApplyAdjustments_Call {
	return &MockStockReservationRepository_ApplyAdjustments_Call{Call: _e.mock.On("ApplyAdjustments", ctx, adjustments)}
}

func (_c *MockStockReservationRepository_ApplyAdjustments_Call) Run(run func(ctx context.Context, adjustments []repository.ReservationAdjustment)) *MockStockReservationRepository_ApplyAdjustments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]repository.ReservationAdjustment))
	})
	return _c
}

func (_c *MockStockReservationRepository_ApplyAdjustments_Call) Return(_a0 error) *MockStockReservationRepository_ApplyAdjustments_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockReservationRepository_ApplyAdjustments_Call) RunAndReturn(run func(context.Context, []repository.ReservationAdjustment) error) *MockStockReservationRepository_ApplyAdjustments_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, r
func (_m *MockStockReservationRepository) Create(ctx context.Context, r *entity.StockReservation) error {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.StockReservation) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockReservationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStockReservationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - r *entity.StockReservation
func (_e *MockStockReservationRepository_Expecter) Create(ctx interface{}, r interface{}) *MockStockReservationRepository_Create_Call {
	return &MockStockReservationRepository_Create_Call{Call: _e.mock.On("Create", ctx, r)}
}

func (_c *MockStockReservationRepository_Create_Call) Run(run func(ctx context.Context, r *entity.StockReservation)) *MockStockReservationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.StockReservation))
	})
	return _c
}

func (_c *MockStockReservationRepository_Create_Call) Return(_a0 error) *MockStockReservationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockReservationRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.StockReservation) error) *MockStockReservationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOrderID provides a mock function with given fields: ctx, orderID
func (_m *MockStockReservationRepository) ListByOrderID(ctx context.Context, orderID uuid.UUID) ([]*entity.StockReservation, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for ListByOrderID")
	}

	var r0 []*entity.StockReservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.StockReservation, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.StockReservation); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.StockReservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStockReservationRepository_ListByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOrderID'
type MockStockReservationRepository_ListByOrderID_Call struct {
	*mock.Call
}

// ListByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockStockReservationRepository_Expecter) ListByOrderID(ctx interface{}, orderID interface{}) *MockStockReservationRepository_ListByOrderID_Call {
	return &MockStockReservationRepository_ListByOrderID_Call{Call: _e.mock.On("ListByOrderID", ctx, orderID)}
}

func (_c *MockStockReservationRepository_ListByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockStockReservationRepository_ListByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStockReservationRepository_ListByOrderID_Call) Return(_a0 []*entity.StockReservation, _a1 error) *MockStockReservationRepository_ListByOrderID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStockReservationRepository_ListByOrderID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.StockReservation, error)) *MockStockReservationRepository_ListByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// ListExpired provides a mock function with given fields: ctx
func (_m *MockStockReservationRepository) ListExpired(ctx context.Context) ([]*entity.StockReservation, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListExpired")
	}

	var r0 []*entity.StockReservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.StockReservation, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.StockReservation); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.StockReservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStockReservationRepository_ListExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExpired'
type MockStockReservationRepository_ListExpired_Call struct {
	*mock.Call
}

// ListExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStockReservationRepository_Expecter) ListExpired(ctx interface{}) *MockStockReservationRepository_ListExpired_Call {
	return &MockStockReservationRepository_ListExpired_Call{Call: _e.mock.On("ListExpired", ctx)}
}

func (_c *MockStockReservationRepository_ListExpired_Call) Run(run func(ctx context.Context)) *MockStockReservationRepository_ListExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStockReservationRepository_ListExpired_Call) Return(_a0 []*entity.StockReservation, _a1 error) *MockStockReservationRepository_ListExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStockReservationRepository_ListExpired_Call) RunAndReturn(run func(context.Context) ([]*entity.StockReservation, error)) *MockStockReservationRepository_ListExpired_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockStockReservationRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status string) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStockReservationRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockStockReservationRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status string
func (_e *MockStockReservationRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockStockReservationRepository_UpdateStatus_Call {
	return &MockStockReservationRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockStockReservationRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status string)) *MockStockReservationRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockStockReservationRepository_UpdateStatus_Call) Return(_a0 error) *MockStockReservationRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStockReservationRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockStockReservationRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStockReservationRepository creates a new instance of MockStockReservationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStockReservationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStockReservationRepository {
	mock := &MockStockReservationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
