// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, o
func (_m *MockOrderRepository) Create(ctx context.Context, o *entity.Order) error {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Order) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - o *entity.Order
func (_e *MockOrderRepository_Expecter) Create(ctx interface{}, o interface{}) *MockOrderRepository_Create_Call {
	return &MockOrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, o)}
}

func (_c *MockOrderRepository_Create_Call) Run(run func(ctx context.Context, o *entity.Order)) *MockOrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Order))
	})
	return _c
}

func (_c *MockOrderRepository_Create_Call) Return(_a0 error) *MockOrderRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Order) error) *MockOrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateItems provides a mock function with given fields: ctx, items
func (_m *MockOrderRepository) CreateItems(ctx context.Context, items []*entity.OrderItem) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateItems")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*entity.OrderItem) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepository_CreateItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItems'
type MockOrderRepository_CreateItems_Call struct {
	*mock.Call
}

// CreateItems is a helper method to define mock.On call
//   - ctx context.Context
//   - items []*entity.OrderItem
func (_e *MockOrderRepository_Expecter) CreateItems(ctx interface{}, items interface{}) *MockOrderRepository_CreateItems_Call {
	return &MockOrderRepository_CreateItems_Call{Call: _e.mock.On("CreateItems", ctx, items)}
}

func (_c *MockOrderRepository_CreateItems_Call) Run(run func(ctx context.Context, items []*entity.OrderItem)) *MockOrderRepository_CreateItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*entity.OrderItem))
	})
	return _c
}

func (_c *MockOrderRepository_CreateItems_Call) Return(_a0 error) *MockOrderRepository_CreateItems_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepository_CreateItems_Call) RunAndReturn(run func(context.Context, []*entity.OrderItem) error) *MockOrderRepository_CreateItems_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockOrderRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockOrderRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockOrderRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockOrderRepository_FindByID_Call {
	return &MockOrderRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockOrderRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOrderRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderRepository_FindByID_Call) Return(_a0 *entity.Order, _a1 error) *MockOrderRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Order, error)) *MockOrderRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindItemByID provides a mock function with given fields: ctx, itemID
func (_m *MockOrderRepository) FindItemByID(ctx context.Context, itemID uuid.UUID) (*entity.OrderItem, error) {
	ret := _m.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for FindItemByID")
	}

	var r0 *entity.OrderItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.OrderItem, error)); ok {
		return rf(ctx, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.OrderItem); ok {
		r0 = rf(ctx, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.OrderItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_FindItemByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindItemByID'
type MockOrderRepository_FindItemByID_Call struct {
	*mock.Call
}

// FindItemByID is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID uuid.UUID
func (_e *MockOrderRepository_Expecter) FindItemByID(ctx interface{}, itemID interface{}) *MockOrderRepository_FindItemByID_Call {
	return &MockOrderRepository_FindItemByID_Call{Call: _e.mock.On("FindItemByID", ctx, itemID)}
}

func (_c *MockOrderRepository_FindItemByID_Call) Run(run func(ctx context.Context, itemID uuid.UUID)) *MockOrderRepository_FindItemByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderRepository_FindItemByID_Call) Return(_a0 *entity.OrderItem, _a1 error) *MockOrderRepository_FindItemByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_FindItemByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.OrderItem, error)) *MockOrderRepository_FindItemByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function with given fields: ctx, page, perPage
func (_m *MockOrderRepository) ListAll(ctx context.Context, page int, perPage int) ([]*entity.Order, int, error) {
	ret := _m.Called(ctx, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []*entity.Order
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*entity.Order, int, error)); ok {
		return rf(ctx, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*entity.Order); ok {
		r0 = rf(ctx, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockOrderRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockOrderRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - perPage int
func (_e *MockOrderRepository_Expecter) ListAll(ctx interface{}, page interface{}, perPage interface{}) *MockOrderRepository_ListAll_Call {
	return &MockOrderRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx, page, perPage)}
}

func (_c *MockOrderRepository_ListAll_Call) Run(run func(ctx context.Context, page int, perPage int)) *MockOrderRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockOrderRepository_ListAll_Call) Return(_a0 []*entity.Order, _a1 int, _a2 error) *MockOrderRepository_ListAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockOrderRepository_ListAll_Call) RunAndReturn(run func(context.Context, int, int) ([]*entity.Order, int, error)) *MockOrderRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCheckoutGroupID provides a mock function with given fields: ctx, checkoutGroupID
func (_m *MockOrderRepository) ListByCheckoutGroupID(ctx context.Context, checkoutGroupID uuid.UUID) ([]*entity.Order, error) {
	ret := _m.Called(ctx, checkoutGroupID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCheckoutGroupID")
	}

	var r0 []*entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Order, error)); ok {
		return rf(ctx, checkoutGroupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Order); ok {
		r0 = rf(ctx, checkoutGroupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, checkoutGroupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_ListByCheckoutGroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCheckoutGroupID'
type MockOrderRepository_ListByCheckoutGroupID_Call struct {
	*mock.Call
}

// ListByCheckoutGroupID is a helper method to define mock.On call
//   - ctx context.Context
//   - checkoutGroupID uuid.UUID
func (_e *MockOrderRepository_Expecter) ListByCheckoutGroupID(ctx interface{}, checkoutGroupID interface{}) *MockOrderRepository_ListByCheckoutGroupID_Call {
	return &MockOrderRepository_ListByCheckoutGroupID_Call{Call: _e.mock.On("ListByCheckoutGroupID", ctx, checkoutGroupID)}
}

func (_c *MockOrderRepository_ListByCheckoutGroupID_Call) Run(run func(ctx context.Context, checkoutGroupID uuid.UUID)) *MockOrderRepository_ListByCheckoutGroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderRepository_ListByCheckoutGroupID_Call) Return(_a0 []*entity.Order, _a1 error) *MockOrderRepository_ListByCheckoutGroupID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_ListByCheckoutGroupID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.Order, error)) *MockOrderRepository_ListByCheckoutGroupID_Call {
	_c.Call.Return(run)
	return _c
}

// ListBySupplierID provides a mock function with given fields: ctx, supplierID, page, perPage
func (_m *MockOrderRepository) ListBySupplierID(ctx context.Context, supplierID uuid.UUID, page int, perPage int) ([]*entity.Order, int, error) {
	ret := _m.Called(ctx, supplierID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for ListBySupplierID")
	}

	var r0 []*entity.Order
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*entity.Order, int, error)); ok {
		return rf(ctx, supplierID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*entity.Order); ok {
		r0 = rf(ctx, supplierID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, supplierID, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, supplierID, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockOrderRepository_ListBySupplierID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBySupplierID'
type MockOrderRepository_ListBySupplierID_Call struct {
	*mock.Call
}

// ListBySupplierID is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID uuid.UUID
//   - page int
//   - perPage int
func (_e *MockOrderRepository_Expecter) ListBySupplierID(ctx interface{}, supplierID interface{}, page interface{}, perPage interface{}) *MockOrderRepository_ListBySupplierID_Call {
	return &MockOrderRepository_ListBySupplierID_Call{Call: _e.mock.On("ListBySupplierID", ctx, supplierID, page, perPage)}
}

func (_c *MockOrderRepository_ListBySupplierID_Call) Run(run func(ctx context.Context, supplierID uuid.UUID, page int, perPage int)) *MockOrderRepository_ListBySupplierID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockOrderRepository_ListBySupplierID_Call) Return(_a0 []*entity.Order, _a1 int, _a2 error) *MockOrderRepository_ListBySupplierID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockOrderRepository_ListBySupplierID_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*entity.Order, int, error)) *MockOrderRepository_ListBySupplierID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID, page, perPage
func (_m *MockOrderRepository) ListByUserID(ctx context.Context, userID uuid.UUID, page int, perPage int) ([]*entity.Order, int, error) {
	ret := _m.Called(ctx, userID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*entity.Order
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*entity.Order, int, error)); ok {
		return rf(ctx, userID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*entity.Order); ok {
		r0 = rf(ctx, userID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, userID, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, userID, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockOrderRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockOrderRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - page int
//   - perPage int
func (_e *MockOrderRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}, page interface{}, perPage interface{}) *MockOrderRepository_ListByUserID_Call {
	return &MockOrderRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, page, perPage)}
}

func (_c *MockOrderRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, page int, perPage int)) *MockOrderRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockOrderRepository_ListByUserID_Call) Return(_a0 []*entity.Order, _a1 int, _a2 error) *MockOrderRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockOrderRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*entity.Order, int, error)) *MockOrderRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeliveredBefore provides a mock function with given fields: ctx, cutoff
func (_m *MockOrderRepository) ListDeliveredBefore(ctx context.Context, cutoff time.Time) ([]*entity.Order, error) {
	ret := _m.Called(ctx, cutoff)

	if len(ret) == 0 {
		panic("no return value specified for ListDeliveredBefore")
	}

	var r0 []*entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]*entity.Order, error)); ok {
		return rf(ctx, cutoff)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []*entity.Order); ok {
		r0 = rf(ctx, cutoff)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, cutoff)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_ListDeliveredBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeliveredBefore'
type MockOrderRepository_ListDeliveredBefore_Call struct {
	*mock.Call
}

// ListDeliveredBefore is a helper method to define mock.On call
//   - ctx context.Context
//   - cutoff time.Time
func (_e *MockOrderRepository_Expecter) ListDeliveredBefore(ctx interface{}, cutoff interface{}) *MockOrderRepository_ListDeliveredBefore_Call {
	return &MockOrderRepository_ListDeliveredBefore_Call{Call: _e.mock.On("ListDeliveredBefore", ctx, cutoff)}
}

func (_c *MockOrderRepository_ListDeliveredBefore_Call) Run(run func(ctx context.Context, cutoff time.Time)) *MockOrderRepository_ListDeliveredBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockOrderRepository_ListDeliveredBefore_Call) Return(_a0 []*entity.Order, _a1 error) *MockOrderRepository_ListDeliveredBefore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_ListDeliveredBefore_Call) RunAndReturn(run func(context.Context, time.Time) ([]*entity.Order, error)) *MockOrderRepository_ListDeliveredBefore_Call {
	_c.Call.Return(run)
	return _c
}

// ListItemsByOrderID provides a mock function with given fields: ctx, orderID
func (_m *MockOrderRepository) ListItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]*entity.OrderItem, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for ListItemsByOrderID")
	}

	var r0 []*entity.OrderItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.OrderItem, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.OrderItem); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.OrderItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_ListItemsByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItemsByOrderID'
type MockOrderRepository_ListItemsByOrderID_Call struct {
	*mock.Call
}

// ListItemsByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderRepository_Expecter) ListItemsByOrderID(ctx interface{}, orderID interface{}) *MockOrderRepository_ListItemsByOrderID_Call {
	return &MockOrderRepository_ListItemsByOrderID_Call{Call: _e.mock.On("ListItemsByOrderID", ctx, orderID)}
}

func (_c *MockOrderRepository_ListItemsByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderRepository_ListItemsByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderRepository_ListItemsByOrderID_Call) Return(_a0 []*entity.OrderItem, _a1 error) *MockOrderRepository_ListItemsByOrderID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_ListItemsByOrderID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.OrderItem, error)) *MockOrderRepository_ListItemsByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// PlatformSalesPerDay provides a mock function with given fields: ctx, from, to
func (_m *MockOrderRepository) PlatformSalesPerDay(ctx context.Context, from time.Time, to time.Time) ([]*entity.DailySales, error) {
	ret := _m.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for PlatformSalesPerDay")
	}

	var r0 []*entity.DailySales
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]*entity.DailySales, error)); ok {
		return rf(ctx, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []*entity.DailySales); ok {
		r0 = rf(ctx, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.DailySales)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_PlatformSalesPerDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlatformSalesPerDay'
type MockOrderRepository_PlatformSalesPerDay_Call struct {
	*mock.Call
}

// PlatformSalesPerDay is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
func (_e *MockOrderRepository_Expecter) PlatformSalesPerDay(ctx interface{}, from interface{}, to interface{}) *MockOrderRepository_PlatformSalesPerDay_Call {
	return &MockOrderRepository_PlatformSalesPerDay_Call{Call: _e.mock.On("PlatformSalesPerDay", ctx, from, to)}
}

func (_c *MockOrderRepository_PlatformSalesPerDay_Call) Run(run func(ctx context.Context, from time.Time, to time.Time)) *MockOrderRepository_PlatformSalesPerDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockOrderRepository_PlatformSalesPerDay_Call) Return(_a0 []*entity.DailySales, _a1 error) *MockOrderRepository_PlatformSalesPerDay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_PlatformSalesPerDay_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) ([]*entity.DailySales, error)) *MockOrderRepository_PlatformSalesPerDay_Call {
	_c.Call.Return(run)
	return _c
}

// PlatformSummary provides a mock function with given fields: ctx, from, to
func (_m *MockOrderRepository) PlatformSummary(ctx context.Context, from time.Time, to time.Time) (float64, map[string]int, error) {
	ret := _m.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for PlatformSummary")
	}

	var r0 float64
	var r1 map[string]int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (float64, map[string]int, error)); ok {
		return rf(ctx, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) float64); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) map[string]int); ok {
		r1 = rf(ctx, from, to)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]int)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, time.Time, time.Time) error); ok {
		r2 = rf(ctx, from, to)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockOrderRepository_PlatformSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlatformSummary'
type MockOrderRepository_PlatformSummary_Call struct {
	*mock.Call
}

// PlatformSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
func (_e *MockOrderRepository_Expecter) PlatformSummary(ctx interface{}, from interface{}, to interface{}) *MockOrderRepository_PlatformSummary_Call {
	return &MockOrderRepository_PlatformSummary_Call{Call: _e.mock.On("PlatformSummary", ctx, from, to)}
}

func (_c *MockOrderRepository_PlatformSummary_Call) Run(run func(ctx context.Context, from time.Time, to time.Time)) *MockOrderRepository_PlatformSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockOrderRepository_PlatformSummary_Call) Return(gmv float64, byStatus map[string]int, err error) *MockOrderRepository_PlatformSummary_Call {
	_c.Call.Return(gmv, byStatus, err)
	return _c
}

func (_c *MockOrderRepository_PlatformSummary_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) (float64, map[string]int, error)) *MockOrderRepository_PlatformSummary_Call {
	_c.Call.Return(run)
	return _c
}

// SalesPerDay provides a mock function with given fields: ctx, supplierID, from, to
func (_m *MockOrderRepository) SalesPerDay(ctx context.Context, supplierID uuid.UUID, from time.Time, to time.Time) ([]*entity.DailySales, error) {
	ret := _m.Called(ctx, supplierID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SalesPerDay")
	}

	var r0 []*entity.DailySales
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]*entity.DailySales, error)); ok {
		return rf(ctx, supplierID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []*entity.DailySales); ok {
		r0 = rf(ctx, supplierID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.DailySales)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, supplierID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_SalesPerDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SalesPerDay'
type MockOrderRepository_SalesPerDay_Call struct {
	*mock.Call
}

// SalesPerDay is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockOrderRepository_Expecter) SalesPerDay(ctx interface{}, supplierID interface{}, from interface{}, to interface{}) *MockOrderRepository_SalesPerDay_Call {
	return &MockOrderRepository_SalesPerDay_Call{Call: _e.mock.On("SalesPerDay", ctx, supplierID, from, to)}
}

func (_c *MockOrderRepository_SalesPerDay_Call) Run(run func(ctx context.Context, supplierID uuid.UUID, from time.Time, to time.Time)) *MockOrderRepository_SalesPerDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockOrderRepository_SalesPerDay_Call) Return(_a0 []*entity.DailySales, _a1 error) *MockOrderRepository_SalesPerDay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_SalesPerDay_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]*entity.DailySales, error)) *MockOrderRepository_SalesPerDay_Call {
	_c.Call.Return(run)
	return _c
}

// SalesSummary provides a mock function with given fields: ctx, supplierID, from, to
func (_m *MockOrderRepository) SalesSummary(ctx context.Context, supplierID uuid.UUID, from time.Time, to time.Time) (float64, int, error) {
	ret := _m.Called(ctx, supplierID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SalesSummary")
	}

	var r0 float64
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) (float64, int, error)); ok {
		return rf(ctx, supplierID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) float64); ok {
		r0 = rf(ctx, supplierID, from, to)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) int); ok {
		r1 = rf(ctx, supplierID, from, to)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r2 = rf(ctx, supplierID, from, to)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockOrderRepository_SalesSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SalesSummary'
type MockOrderRepository_SalesSummary_Call struct {
	*mock.Call
}

// SalesSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockOrderRepository_Expecter) SalesSummary(ctx interface{}, supplierID interface{}, from interface{}, to interface{}) *MockOrderRepository_SalesSummary_Call {
	return &MockOrderRepository_SalesSummary_Call{Call: _e.mock.On("SalesSummary", ctx, supplierID, from, to)}
}

func (_c *MockOrderRepository_SalesSummary_Call) Run(run func(ctx context.Context, supplierID uuid.UUID, from time.Time, to time.Time)) *MockOrderRepository_SalesSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockOrderRepository_SalesSummary_Call) Return(gmv float64, ordersCount int, err error) *MockOrderRepository_SalesSummary_Call {
	_c.Call.Return(gmv, ordersCount, err)
	return _c
}

func (_c *MockOrderRepository_SalesSummary_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) (float64, int, error)) *MockOrderRepository_SalesSummary_Call {
	_c.Call.Return(run)
	return _c
}

// TopProducts provides a mock function with given fields: ctx, supplierID, from, to, limit
func (_m *MockOrderRepository) TopProducts(ctx context.Context, supplierID uuid.UUID, from time.Time, to time.Time, limit int) ([]*entity.TopProduct, error) {
	ret := _m.Called(ctx, supplierID, from, to, limit)

	if len(ret) == 0 {
		panic("no return value specified for TopProducts")
	}

	var r0 []*entity.TopProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time, int) ([]*entity.TopProduct, error)); ok {
		return rf(ctx, supplierID, from, to, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time, int) []*entity.TopProduct); ok {
		r0 = rf(ctx, supplierID, from, to, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TopProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time, int) error); ok {
		r1 = rf(ctx, supplierID, from, to, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_TopProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopProducts'
type MockOrderRepository_TopProducts_Call struct {
	*mock.Call
}

// TopProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID uuid.UUID
//   - from time.Time
//   - to time.Time
//   - limit int
func (_e *MockOrderRepository_Expecter) TopProducts(ctx interface{}, supplierID interface{}, from interface{}, to interface{}, limit interface{}) *MockOrderRepository_TopProducts_Call {
	return &MockOrderRepository_TopProducts_Call{Call: _e.mock.On("TopProducts", ctx, supplierID, from, to, limit)}
}

func (_c *MockOrderRepository_TopProducts_Call) Run(run func(ctx context.Context, supplierID uuid.UUID, from time.Time, to time.Time, limit int)) *MockOrderRepository_TopProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time), args[4].(int))
	})
	return _c
}

func (_c *MockOrderRepository_TopProducts_Call) Return(_a0 []*entity.TopProduct, _a1 error) *MockOrderRepository_TopProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_TopProducts_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time, int) ([]*entity.TopProduct, error)) *MockOrderRepository_TopProducts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockOrderRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status string) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockOrderRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status string
func (_e *MockOrderRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockOrderRepository_UpdateStatus_Call {
	return &MockOrderRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockOrderRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status string)) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockOrderRepository_UpdateStatus_Call) Return(_a0 error) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
