// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockPaymentRepository is an autogenerated mock type for the PaymentRepository type
type MockPaymentRepository struct {
	mock.Mock
}

type MockPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRepository) EXPECT() *MockPaymentRepository_Expecter {
	return &MockPaymentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, p
func (_m *MockPaymentRepository) Create(ctx context.Context, p *entity.Payment) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Payment) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPaymentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p *entity.Payment
func (_e *MockPaymentRepository_Expecter) Create(ctx interface{}, p interface{}) *MockPaymentRepository_Create_Call {
	return &MockPaymentRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockPaymentRepository_Create_Call) Run(run func(ctx context.Context, p *entity.Payment)) *MockPaymentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Payment))
	})
	return _c
}

func (_c *MockPaymentRepository_Create_Call) Return(_a0 error) *MockPaymentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Payment) error) *MockPaymentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCheckoutGroupID provides a mock function with given fields: ctx, checkoutGroupID
func (_m *MockPaymentRepository) FindByCheckoutGroupID(ctx context.Context, checkoutGroupID uuid.UUID) (*entity.Payment, error) {
	ret := _m.Called(ctx, checkoutGroupID)

	if len(ret) == 0 {
		panic("no return value specified for FindByCheckoutGroupID")
	}

	var r0 *entity.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Payment, error)); ok {
		return rf(ctx, checkoutGroupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Payment); ok {
		r0 = rf(ctx, checkoutGroupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, checkoutGroupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_FindByCheckoutGroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCheckoutGroupID'
type MockPaymentRepository_FindByCheckoutGroupID_Call struct {
	*mock.Call
}

// FindByCheckoutGroupID is a helper method to define mock.On call
//   - ctx context.Context
//   - checkoutGroupID uuid.UUID
func (_e *MockPaymentRepository_Expecter) FindByCheckoutGroupID(ctx interface{}, checkoutGroupID interface{}) *MockPaymentRepository_FindByCheckoutGroupID_Call {
	return &MockPaymentRepository_FindByCheckoutGroupID_Call{Call: _e.mock.On("FindByCheckoutGroupID", ctx, checkoutGroupID)}
}

func (_c *MockPaymentRepository_FindByCheckoutGroupID_Call) Run(run func(ctx context.Context, checkoutGroupID uuid.UUID)) *MockPaymentRepository_FindByCheckoutGroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPaymentRepository_FindByCheckoutGroupID_Call) Return(_a0 *entity.Payment, _a1 error) *MockPaymentRepository_FindByCheckoutGroupID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_FindByCheckoutGroupID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Payment, error)) *MockPaymentRepository_FindByCheckoutGroupID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByXenditInvoiceID provides a mock function with given fields: ctx, xenditInvoiceID
func (_m *MockPaymentRepository) FindByXenditInvoiceID(ctx context.Context, xenditInvoiceID string) (*entity.Payment, error) {
	ret := _m.Called(ctx, xenditInvoiceID)

	if len(ret) == 0 {
		panic("no return value specified for FindByXenditInvoiceID")
	}

	var r0 *entity.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Payment, error)); ok {
		return rf(ctx, xenditInvoiceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Payment); ok {
		r0 = rf(ctx, xenditInvoiceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, xenditInvoiceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_FindByXenditInvoiceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByXenditInvoiceID'
type MockPaymentRepository_FindByXenditInvoiceID_Call struct {
	*mock.Call
}

// FindByXenditInvoiceID is a helper method to define mock.On call
//   - ctx context.Context
//   - xenditInvoiceID string
func (_e *MockPaymentRepository_Expecter) FindByXenditInvoiceID(ctx interface{}, xenditInvoiceID interface{}) *MockPaymentRepository_FindByXenditInvoiceID_Call {
	return &MockPaymentRepository_FindByXenditInvoiceID_Call{Call: _e.mock.On("FindByXenditInvoiceID", ctx, xenditInvoiceID)}
}

func (_c *MockPaymentRepository_FindByXenditInvoiceID_Call) Run(run func(ctx context.Context, xenditInvoiceID string)) *MockPaymentRepository_FindByXenditInvoiceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentRepository_FindByXenditInvoiceID_Call) Return(_a0 *entity.Payment, _a1 error) *MockPaymentRepository_FindByXenditInvoiceID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_FindByXenditInvoiceID_Call) RunAndReturn(run func(context.Context, string) (*entity.Payment, error)) *MockPaymentRepository_FindByXenditInvoiceID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPaid provides a mock function with given fields: ctx, id, paidAt
func (_m *MockPaymentRepository) MarkPaid(ctx context.Context, id uuid.UUID, paidAt time.Time) error {
	ret := _m.Called(ctx, id, paidAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkPaid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, id, paidAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepository_MarkPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPaid'
type MockPaymentRepository_MarkPaid_Call struct {
	*mock.Call
}

// MarkPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - paidAt time.Time
func (_e *MockPaymentRepository_Expecter) MarkPaid(ctx interface{}, id interface{}, paidAt interface{}) *MockPaymentRepository_MarkPaid_Call {
	return &MockPaymentRepository_MarkPaid_Call{Call: _e.mock.On("MarkPaid", ctx, id, paidAt)}
}

func (_c *MockPaymentRepository_MarkPaid_Call) Run(run func(ctx context.Context, id uuid.UUID, paidAt time.Time)) *MockPaymentRepository_MarkPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockPaymentRepository_MarkPaid_Call) Return(_a0 error) *MockPaymentRepository_MarkPaid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepository_MarkPaid_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockPaymentRepository_MarkPaid_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentRepository creates a new instance of MockPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepository {
	mock := &MockPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
