// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockCategoryRepository is an autogenerated mock type for the CategoryRepository type
type MockCategoryRepository struct {
	mock.Mock
}

type MockCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryRepository) EXPECT() *MockCategoryRepository_Expecter {
	return &MockCategoryRepository_Expecter{mock: &_m.Mock}
}

// CountChildren provides a mock function with given fields: ctx, id
func (_m *MockCategoryRepository) CountChildren(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountChildren")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_CountChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountChildren'
type MockCategoryRepository_CountChildren_Call struct {
	*mock.Call
}

// CountChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockCategoryRepository_Expecter) CountChildren(ctx interface{}, id interface{}) *MockCategoryRepository_CountChildren_Call {
	return &MockCategoryRepository_CountChildren_Call{Call: _e.mock.On("CountChildren", ctx, id)}
}

func (_c *MockCategoryRepository_CountChildren_Call) Run(run func(ctx context.Context, id int)) *MockCategoryRepository_CountChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockCategoryRepository_CountChildren_Call) Return(_a0 int, _a1 error) *MockCategoryRepository_CountChildren_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_CountChildren_Call) RunAndReturn(run func(context.Context, int) (int, error)) *MockCategoryRepository_CountChildren_Call {
	_c.Call.Return(run)
	return _c
}

// CountProducts provides a mock function with given fields: ctx, id
func (_m *MockCategoryRepository) CountProducts(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountProducts")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_CountProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountProducts'
type MockCategoryRepository_CountProducts_Call struct {
	*mock.Call
}

// CountProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockCategoryRepository_Expecter) CountProducts(ctx interface{}, id interface{}) *MockCategoryRepository_CountProducts_Call {
	return &MockCategoryRepository_CountProducts_Call{Call: _e.mock.On("CountProducts", ctx, id)}
}

func (_c *MockCategoryRepository_CountProducts_Call) Run(run func(ctx context.Context, id int)) *MockCategoryRepository_CountProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockCategoryRepository_CountProducts_Call) Return(_a0 int, _a1 error) *MockCategoryRepository_CountProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_CountProducts_Call) RunAndReturn(run func(context.Context, int) (int, error)) *MockCategoryRepository_CountProducts_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, c
func (_m *MockCategoryRepository) Create(ctx context.Context, c *entity.Category) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Category) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - c *entity.Category
func (_e *MockCategoryRepository_Expecter) Create(ctx interface{}, c interface{}) *MockCategoryRepository_Create_Call {
	return &MockCategoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, c)}
}

func (_c *MockCategoryRepository_Create_Call) Run(run func(ctx context.Context, c *entity.Category)) *MockCategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Category))
	})
	return _c
}

func (_c *MockCategoryRepository_Create_Call) Return(_a0 error) *MockCategoryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Category) error) *MockCategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCategoryRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockCategoryRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockCategoryRepository_Delete_Call {
	return &MockCategoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCategoryRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockCategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockCategoryRepository_Delete_Call) Return(_a0 error) *MockCategoryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryRepository_Delete_Call) RunAndReturn(run func(context.Context, int) error) *MockCategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockCategoryRepository) FindByID(ctx context.Context, id int) (*entity.Category, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*entity.Category, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *entity.Category); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCategoryRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockCategoryRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockCategoryRepository_FindByID_Call {
	return &MockCategoryRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCategoryRepository_FindByID_Call) Run(run func(ctx context.Context, id int)) *MockCategoryRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockCategoryRepository_FindByID_Call) Return(_a0 *entity.Category, _a1 error) *MockCategoryRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_FindByID_Call) RunAndReturn(run func(context.Context, int) (*entity.Category, error)) *MockCategoryRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySlug provides a mock function with given fields: ctx, slug
func (_m *MockCategoryRepository) FindBySlug(ctx context.Context, slug string) (*entity.Category, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindBySlug")
	}

	var r0 *entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Category, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Category); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_FindBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySlug'
type MockCategoryRepository_FindBySlug_Call struct {
	*mock.Call
}

// FindBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockCategoryRepository_Expecter) FindBySlug(ctx interface{}, slug interface{}) *MockCategoryRepository_FindBySlug_Call {
	return &MockCategoryRepository_FindBySlug_Call{Call: _e.mock.On("FindBySlug", ctx, slug)}
}

func (_c *MockCategoryRepository_FindBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockCategoryRepository_FindBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCategoryRepository_FindBySlug_Call) Return(_a0 *entity.Category, _a1 error) *MockCategoryRepository_FindBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_FindBySlug_Call) RunAndReturn(run func(context.Context, string) (*entity.Category, error)) *MockCategoryRepository_FindBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// ListTree provides a mock function with given fields: ctx
func (_m *MockCategoryRepository) ListTree(ctx context.Context) ([]*entity.Category, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTree")
	}

	var r0 []*entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Category, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Category); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_ListTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTree'
type MockCategoryRepository_ListTree_Call struct {
	*mock.Call
}

// ListTree is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCategoryRepository_Expecter) ListTree(ctx interface{}) *MockCategoryRepository_ListTree_Call {
	return &MockCategoryRepository_ListTree_Call{Call: _e.mock.On("ListTree", ctx)}
}

func (_c *MockCategoryRepository_ListTree_Call) Run(run func(ctx context.Context)) *MockCategoryRepository_ListTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCategoryRepository_ListTree_Call) Return(_a0 []*entity.Category, _a1 error) *MockCategoryRepository_ListTree_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_ListTree_Call) RunAndReturn(run func(context.Context) ([]*entity.Category, error)) *MockCategoryRepository_ListTree_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, c
func (_m *MockCategoryRepository) Update(ctx context.Context, c *entity.Category) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Category) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - c *entity.Category
func (_e *MockCategoryRepository_Expecter) Update(ctx interface{}, c interface{}) *MockCategoryRepository_Update_Call {
	return &MockCategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, c)}
}

func (_c *MockCategoryRepository_Update_Call) Run(run func(ctx context.Context, c *entity.Category)) *MockCategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Category))
	})
	return _c
}

func (_c *MockCategoryRepository_Update_Call) Return(_a0 error) *MockCategoryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Category) error) *MockCategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategoryRepository creates a new instance of MockCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryRepository {
	mock := &MockCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
