// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockOrderStatusHistoryRepository is an autogenerated mock type for the OrderStatusHistoryRepository type
type MockOrderStatusHistoryRepository struct {
	mock.Mock
}

type MockOrderStatusHistoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderStatusHistoryRepository) EXPECT() *MockOrderStatusHistoryRepository_Expecter {
	return &MockOrderStatusHistoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, h
func (_m *MockOrderStatusHistoryRepository) Create(ctx context.Context, h *entity.OrderStatusHistory) error {
	ret := _m.Called(ctx, h)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.OrderStatusHistory) error); ok {
		r0 = rf(ctx, h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderStatusHistoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderStatusHistoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - h *entity.OrderStatusHistory
func (_e *MockOrderStatusHistoryRepository_Expecter) Create(ctx interface{}, h interface{}) *MockOrderStatusHistoryRepository_Create_Call {
	return &MockOrderStatusHistoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, h)}
}

func (_c *MockOrderStatusHistoryRepository_Create_Call) Run(run func(ctx context.Context, h *entity.OrderStatusHistory)) *MockOrderStatusHistoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.OrderStatusHistory))
	})
	return _c
}

func (_c *MockOrderStatusHistoryRepository_Create_Call) Return(_a0 error) *MockOrderStatusHistoryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderStatusHistoryRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.OrderStatusHistory) error) *MockOrderStatusHistoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOrderID provides a mock function with given fields: ctx, orderID
func (_m *MockOrderStatusHistoryRepository) ListByOrderID(ctx context.Context, orderID uuid.UUID) ([]*entity.OrderStatusHistory, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for ListByOrderID")
	}

	var r0 []*entity.OrderStatusHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.OrderStatusHistory, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.OrderStatusHistory); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.OrderStatusHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderStatusHistoryRepository_ListByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOrderID'
type MockOrderStatusHistoryRepository_ListByOrderID_Call struct {
	*mock.Call
}

// ListByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderStatusHistoryRepository_Expecter) ListByOrderID(ctx interface{}, orderID interface{}) *MockOrderStatusHistoryRepository_ListByOrderID_Call {
	return &MockOrderStatusHistoryRepository_ListByOrderID_Call{Call: _e.mock.On("ListByOrderID", ctx, orderID)}
}

func (_c *MockOrderStatusHistoryRepository_ListByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderStatusHistoryRepository_ListByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderStatusHistoryRepository_ListByOrderID_Call) Return(_a0 []*entity.OrderStatusHistory, _a1 error) *MockOrderStatusHistoryRepository_ListByOrderID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderStatusHistoryRepository_ListByOrderID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.OrderStatusHistory, error)) *MockOrderStatusHistoryRepository_ListByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderStatusHistoryRepository creates a new instance of MockOrderStatusHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderStatusHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderStatusHistoryRepository {
	mock := &MockOrderStatusHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
