// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSupplierDocumentRepository is an autogenerated mock type for the SupplierDocumentRepository type
type MockSupplierDocumentRepository struct {
	mock.Mock
}

type MockSupplierDocumentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSupplierDocumentRepository) EXPECT() *MockSupplierDocumentRepository_Expecter {
	return &MockSupplierDocumentRepository_Expecter{mock: &_m.Mock}
}

// FindBySupplierAndType provides a mock function with given fields: ctx, supplierID, docType
func (_m *MockSupplierDocumentRepository) FindBySupplierAndType(ctx context.Context, supplierID uuid.UUID, docType string) (*entity.SupplierDocument, error) {
	ret := _m.Called(ctx, supplierID, docType)

	if len(ret) == 0 {
		panic("no return value specified for FindBySupplierAndType")
	}

	var r0 *entity.SupplierDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*entity.SupplierDocument, error)); ok {
		return rf(ctx, supplierID, docType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *entity.SupplierDocument); ok {
		r0 = rf(ctx, supplierID, docType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SupplierDocument)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, supplierID, docType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplierDocumentRepository_FindBySupplierAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySupplierAndType'
type MockSupplierDocumentRepository_FindBySupplierAndType_Call struct {
	*mock.Call
}

// FindBySupplierAndType is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID uuid.UUID
//   - docType string
func (_e *MockSupplierDocumentRepository_Expecter) FindBySupplierAndType(ctx interface{}, supplierID interface{}, docType interface{}) *MockSupplierDocumentRepository_FindBySupplierAndType_Call {
	return &MockSupplierDocumentRepository_FindBySupplierAndType_Call{Call: _e.mock.On("FindBySupplierAndType", ctx, supplierID, docType)}
}

func (_c *MockSupplierDocumentRepository_FindBySupplierAndType_Call) Run(run func(ctx context.Context, supplierID uuid.UUID, docType string)) *MockSupplierDocumentRepository_FindBySupplierAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockSupplierDocumentRepository_FindBySupplierAndType_Call) Return(_a0 *entity.SupplierDocument, _a1 error) *MockSupplierDocumentRepository_FindBySupplierAndType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupplierDocumentRepository_FindBySupplierAndType_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*entity.SupplierDocument, error)) *MockSupplierDocumentRepository_FindBySupplierAndType_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySupplierID provides a mock function with given fields: ctx, supplierID
func (_m *MockSupplierDocumentRepository) FindBySupplierID(ctx context.Context, supplierID uuid.UUID) ([]*entity.SupplierDocument, error) {
	ret := _m.Called(ctx, supplierID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySupplierID")
	}

	var r0 []*entity.SupplierDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.SupplierDocument, error)); ok {
		return rf(ctx, supplierID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.SupplierDocument); ok {
		r0 = rf(ctx, supplierID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.SupplierDocument)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, supplierID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplierDocumentRepository_FindBySupplierID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySupplierID'
type MockSupplierDocumentRepository_FindBySupplierID_Call struct {
	*mock.Call
}

// FindBySupplierID is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID uuid.UUID
func (_e *MockSupplierDocumentRepository_Expecter) FindBySupplierID(ctx interface{}, supplierID interface{}) *MockSupplierDocumentRepository_FindBySupplierID_Call {
	return &MockSupplierDocumentRepository_FindBySupplierID_Call{Call: _e.mock.On("FindBySupplierID", ctx, supplierID)}
}

func (_c *MockSupplierDocumentRepository_FindBySupplierID_Call) Run(run func(ctx context.Context, supplierID uuid.UUID)) *MockSupplierDocumentRepository_FindBySupplierID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSupplierDocumentRepository_FindBySupplierID_Call) Return(_a0 []*entity.SupplierDocument, _a1 error) *MockSupplierDocumentRepository_FindBySupplierID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupplierDocumentRepository_FindBySupplierID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.SupplierDocument, error)) *MockSupplierDocumentRepository_FindBySupplierID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, d
func (_m *MockSupplierDocumentRepository) Upsert(ctx context.Context, d *entity.SupplierDocument) error {
	ret := _m.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SupplierDocument) error); ok {
		r0 = rf(ctx, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupplierDocumentRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockSupplierDocumentRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - d *entity.SupplierDocument
func (_e *MockSupplierDocumentRepository_Expecter) Upsert(ctx interface{}, d interface{}) *MockSupplierDocumentRepository_Upsert_Call {
	return &MockSupplierDocumentRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, d)}
}

func (_c *MockSupplierDocumentRepository_Upsert_Call) Run(run func(ctx context.Context, d *entity.SupplierDocument)) *MockSupplierDocumentRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.SupplierDocument))
	})
	return _c
}

func (_c *MockSupplierDocumentRepository_Upsert_Call) Return(_a0 error) *MockSupplierDocumentRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupplierDocumentRepository_Upsert_Call) RunAndReturn(run func(context.Context, *entity.SupplierDocument) error) *MockSupplierDocumentRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSupplierDocumentRepository creates a new instance of MockSupplierDocumentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSupplierDocumentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSupplierDocumentRepository {
	mock := &MockSupplierDocumentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
