// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	repository "erdinhrmwn/bangunin/internal/domain/repository"

	uuid "github.com/google/uuid"
)

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, p
func (_m *MockProductRepository) Create(ctx context.Context, p *entity.Product) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Product) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p *entity.Product
func (_e *MockProductRepository_Expecter) Create(ctx interface{}, p interface{}) *MockProductRepository_Create_Call {
	return &MockProductRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockProductRepository_Create_Call) Run(run func(ctx context.Context, p *entity.Product)) *MockProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Product))
	})
	return _c
}

func (_c *MockProductRepository_Create_Call) Return(_a0 error) *MockProductRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Product) error) *MockProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockProductRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockProductRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProductRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockProductRepository_FindByID_Call {
	return &MockProductRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockProductRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProductRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductRepository_FindByID_Call) Return(_a0 *entity.Product, _a1 error) *MockProductRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Product, error)) *MockProductRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function with given fields: ctx, ids
func (_m *MockProductRepository) FindByIDs(ctx context.Context, ids []uuid.UUID) ([]*entity.Product, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []*entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]*entity.Product, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []*entity.Product); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type MockProductRepository_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockProductRepository_Expecter) FindByIDs(ctx interface{}, ids interface{}) *MockProductRepository_FindByIDs_Call {
	return &MockProductRepository_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, ids)}
}

func (_c *MockProductRepository_FindByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockProductRepository_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockProductRepository_FindByIDs_Call) Return(_a0 []*entity.Product, _a1 error) *MockProductRepository_FindByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_FindByIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]*entity.Product, error)) *MockProductRepository_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySlug provides a mock function with given fields: ctx, slug
func (_m *MockProductRepository) FindBySlug(ctx context.Context, slug string) (*entity.Product, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindBySlug")
	}

	var r0 *entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Product, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Product); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_FindBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySlug'
type MockProductRepository_FindBySlug_Call struct {
	*mock.Call
}

// FindBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockProductRepository_Expecter) FindBySlug(ctx interface{}, slug interface{}) *MockProductRepository_FindBySlug_Call {
	return &MockProductRepository_FindBySlug_Call{Call: _e.mock.On("FindBySlug", ctx, slug)}
}

func (_c *MockProductRepository_FindBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockProductRepository_FindBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProductRepository_FindBySlug_Call) Return(_a0 *entity.Product, _a1 error) *MockProductRepository_FindBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_FindBySlug_Call) RunAndReturn(run func(context.Context, string) (*entity.Product, error)) *MockProductRepository_FindBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySupplierAndID provides a mock function with given fields: ctx, supplierID, id
func (_m *MockProductRepository) FindBySupplierAndID(ctx context.Context, supplierID uuid.UUID, id uuid.UUID) (*entity.Product, error) {
	ret := _m.Called(ctx, supplierID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindBySupplierAndID")
	}

	var r0 *entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*entity.Product, error)); ok {
		return rf(ctx, supplierID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *entity.Product); ok {
		r0 = rf(ctx, supplierID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, supplierID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_FindBySupplierAndID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySupplierAndID'
type MockProductRepository_FindBySupplierAndID_Call struct {
	*mock.Call
}

// FindBySupplierAndID is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID uuid.UUID
//   - id uuid.UUID
func (_e *MockProductRepository_Expecter) FindBySupplierAndID(ctx interface{}, supplierID interface{}, id interface{}) *MockProductRepository_FindBySupplierAndID_Call {
	return &MockProductRepository_FindBySupplierAndID_Call{Call: _e.mock.On("FindBySupplierAndID", ctx, supplierID, id)}
}

func (_c *MockProductRepository_FindBySupplierAndID_Call) Run(run func(ctx context.Context, supplierID uuid.UUID, id uuid.UUID)) *MockProductRepository_FindBySupplierAndID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductRepository_FindBySupplierAndID_Call) Return(_a0 *entity.Product, _a1 error) *MockProductRepository_FindBySupplierAndID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_FindBySupplierAndID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*entity.Product, error)) *MockProductRepository_FindBySupplierAndID_Call {
	_c.Call.Return(run)
	return _c
}

// ListBySupplier provides a mock function with given fields: ctx, supplierID, page, perPage
func (_m *MockProductRepository) ListBySupplier(ctx context.Context, supplierID uuid.UUID, page int, perPage int) ([]*entity.Product, int, error) {
	ret := _m.Called(ctx, supplierID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for ListBySupplier")
	}

	var r0 []*entity.Product
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*entity.Product, int, error)); ok {
		return rf(ctx, supplierID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*entity.Product); ok {
		r0 = rf(ctx, supplierID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, supplierID, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, supplierID, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockProductRepository_ListBySupplier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBySupplier'
type MockProductRepository_ListBySupplier_Call struct {
	*mock.Call
}

// ListBySupplier is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID uuid.UUID
//   - page int
//   - perPage int
func (_e *MockProductRepository_Expecter) ListBySupplier(ctx interface{}, supplierID interface{}, page interface{}, perPage interface{}) *MockProductRepository_ListBySupplier_Call {
	return &MockProductRepository_ListBySupplier_Call{Call: _e.mock.On("ListBySupplier", ctx, supplierID, page, perPage)}
}

func (_c *MockProductRepository_ListBySupplier_Call) Run(run func(ctx context.Context, supplierID uuid.UUID, page int, perPage int)) *MockProductRepository_ListBySupplier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockProductRepository_ListBySupplier_Call) Return(_a0 []*entity.Product, _a1 int, _a2 error) *MockProductRepository_ListBySupplier_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockProductRepository_ListBySupplier_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*entity.Product, int, error)) *MockProductRepository_ListBySupplier_Call {
	_c.Call.Return(run)
	return _c
}

// ListBySupplierPublic provides a mock function with given fields: ctx, supplierID, page, perPage
func (_m *MockProductRepository) ListBySupplierPublic(ctx context.Context, supplierID uuid.UUID, page int, perPage int) ([]*entity.Product, int, error) {
	ret := _m.Called(ctx, supplierID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for ListBySupplierPublic")
	}

	var r0 []*entity.Product
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*entity.Product, int, error)); ok {
		return rf(ctx, supplierID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*entity.Product); ok {
		r0 = rf(ctx, supplierID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, supplierID, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, supplierID, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockProductRepository_ListBySupplierPublic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBySupplierPublic'
type MockProductRepository_ListBySupplierPublic_Call struct {
	*mock.Call
}

// ListBySupplierPublic is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID uuid.UUID
//   - page int
//   - perPage int
func (_e *MockProductRepository_Expecter) ListBySupplierPublic(ctx interface{}, supplierID interface{}, page interface{}, perPage interface{}) *MockProductRepository_ListBySupplierPublic_Call {
	return &MockProductRepository_ListBySupplierPublic_Call{Call: _e.mock.On("ListBySupplierPublic", ctx, supplierID, page, perPage)}
}

func (_c *MockProductRepository_ListBySupplierPublic_Call) Run(run func(ctx context.Context, supplierID uuid.UUID, page int, perPage int)) *MockProductRepository_ListBySupplierPublic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockProductRepository_ListBySupplierPublic_Call) Return(_a0 []*entity.Product, _a1 int, _a2 error) *MockProductRepository_ListBySupplierPublic_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockProductRepository_ListBySupplierPublic_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*entity.Product, int, error)) *MockProductRepository_ListBySupplierPublic_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, params
func (_m *MockProductRepository) Search(ctx context.Context, params repository.SearchParams) ([]*repository.ProductSummary, string, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*repository.ProductSummary
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.SearchParams) ([]*repository.ProductSummary, string, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.SearchParams) []*repository.ProductSummary); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.ProductSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.SearchParams) string); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.SearchParams) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockProductRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockProductRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - params repository.SearchParams
func (_e *MockProductRepository_Expecter) Search(ctx interface{}, params interface{}) *MockProductRepository_Search_Call {
	return &MockProductRepository_Search_Call{Call: _e.mock.On("Search", ctx, params)}
}

func (_c *MockProductRepository_Search_Call) Run(run func(ctx context.Context, params repository.SearchParams)) *MockProductRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.SearchParams))
	})
	return _c
}

func (_c *MockProductRepository_Search_Call) Return(_a0 []*repository.ProductSummary, _a1 string, _a2 error) *MockProductRepository_Search_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockProductRepository_Search_Call) RunAndReturn(run func(context.Context, repository.SearchParams) ([]*repository.ProductSummary, string, error)) *MockProductRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, p
func (_m *MockProductRepository) Update(ctx context.Context, p *entity.Product) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Product) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p *entity.Product
func (_e *MockProductRepository_Expecter) Update(ctx interface{}, p interface{}) *MockProductRepository_Update_Call {
	return &MockProductRepository_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *MockProductRepository_Update_Call) Run(run func(ctx context.Context, p *entity.Product)) *MockProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Product))
	})
	return _c
}

func (_c *MockProductRepository_Update_Call) Return(_a0 error) *MockProductRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Product) error) *MockProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRating provides a mock function with given fields: ctx, productID, avg, count
func (_m *MockProductRepository) UpdateRating(ctx context.Context, productID uuid.UUID, avg float64, count int) error {
	ret := _m.Called(ctx, productID, avg, count)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRating")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64, int) error); ok {
		r0 = rf(ctx, productID, avg, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_UpdateRating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRating'
type MockProductRepository_UpdateRating_Call struct {
	*mock.Call
}

// UpdateRating is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
//   - avg float64
//   - count int
func (_e *MockProductRepository_Expecter) UpdateRating(ctx interface{}, productID interface{}, avg interface{}, count interface{}) *MockProductRepository_UpdateRating_Call {
	return &MockProductRepository_UpdateRating_Call{Call: _e.mock.On("UpdateRating", ctx, productID, avg, count)}
}

func (_c *MockProductRepository_UpdateRating_Call) Run(run func(ctx context.Context, productID uuid.UUID, avg float64, count int)) *MockProductRepository_UpdateRating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(float64), args[3].(int))
	})
	return _c
}

func (_c *MockProductRepository_UpdateRating_Call) Return(_a0 error) *MockProductRepository_UpdateRating_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_UpdateRating_Call) RunAndReturn(run func(context.Context, uuid.UUID, float64, int) error) *MockProductRepository_UpdateRating_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
