// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockNotificationRepository is an autogenerated mock type for the NotificationRepository type
type MockNotificationRepository struct {
	mock.Mock
}

type MockNotificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationRepository) EXPECT() *MockNotificationRepository_Expecter {
	return &MockNotificationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, n
func (_m *MockNotificationRepository) Create(ctx context.Context, n *entity.Notification) error {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Notification) error); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockNotificationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - n *entity.Notification
func (_e *MockNotificationRepository_Expecter) Create(ctx interface{}, n interface{}) *MockNotificationRepository_Create_Call {
	return &MockNotificationRepository_Create_Call{Call: _e.mock.On("Create", ctx, n)}
}

func (_c *MockNotificationRepository_Create_Call) Run(run func(ctx context.Context, n *entity.Notification)) *MockNotificationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Notification))
	})
	return _c
}

func (_c *MockNotificationRepository_Create_Call) Return(_a0 error) *MockNotificationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Notification) error) *MockNotificationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID, page, perPage
func (_m *MockNotificationRepository) FindByUserID(ctx context.Context, userID uuid.UUID, page int, perPage int) ([]*entity.Notification, int, error) {
	ret := _m.Called(ctx, userID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*entity.Notification
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*entity.Notification, int, error)); ok {
		return rf(ctx, userID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*entity.Notification); ok {
		r0 = rf(ctx, userID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, userID, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, userID, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockNotificationRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockNotificationRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - page int
//   - perPage int
func (_e *MockNotificationRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}, page interface{}, perPage interface{}) *MockNotificationRepository_FindByUserID_Call {
	return &MockNotificationRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID, page, perPage)}
}

func (_c *MockNotificationRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, page int, perPage int)) *MockNotificationRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockNotificationRepository_FindByUserID_Call) Return(_a0 []*entity.Notification, _a1 int, _a2 error) *MockNotificationRepository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockNotificationRepository_FindByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*entity.Notification, int, error)) *MockNotificationRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function with given fields: ctx, id, userID
func (_m *MockNotificationRepository) MarkRead(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationRepository_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockNotificationRepository_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockNotificationRepository_Expecter) MarkRead(ctx interface{}, id interface{}, userID interface{}) *MockNotificationRepository_MarkRead_Call {
	return &MockNotificationRepository_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, id, userID)}
}

func (_c *MockNotificationRepository_MarkRead_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockNotificationRepository_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockNotificationRepository_MarkRead_Call) Return(_a0 error) *MockNotificationRepository_MarkRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationRepository_MarkRead_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockNotificationRepository_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationRepository creates a new instance of MockNotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationRepository {
	mock := &MockNotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
