// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockReviewRepository is an autogenerated mock type for the ReviewRepository type
type MockReviewRepository struct {
	mock.Mock
}

type MockReviewRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewRepository) EXPECT() *MockReviewRepository_Expecter {
	return &MockReviewRepository_Expecter{mock: &_m.Mock}
}

// AverageRating provides a mock function with given fields: ctx, productID
func (_m *MockReviewRepository) AverageRating(ctx context.Context, productID uuid.UUID) (float64, int, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for AverageRating")
	}

	var r0 float64
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (float64, int, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) float64); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) int); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, productID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockReviewRepository_AverageRating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AverageRating'
type MockReviewRepository_AverageRating_Call struct {
	*mock.Call
}

// AverageRating is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockReviewRepository_Expecter) AverageRating(ctx interface{}, productID interface{}) *MockReviewRepository_AverageRating_Call {
	return &MockReviewRepository_AverageRating_Call{Call: _e.mock.On("AverageRating", ctx, productID)}
}

func (_c *MockReviewRepository_AverageRating_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockReviewRepository_AverageRating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockReviewRepository_AverageRating_Call) Return(avg float64, count int, err error) *MockReviewRepository_AverageRating_Call {
	_c.Call.Return(avg, count, err)
	return _c
}

func (_c *MockReviewRepository_AverageRating_Call) RunAndReturn(run func(context.Context, uuid.UUID) (float64, int, error)) *MockReviewRepository_AverageRating_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, r
func (_m *MockReviewRepository) Create(ctx context.Context, r *entity.Review) error {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Review) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReviewRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReviewRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - r *entity.Review
func (_e *MockReviewRepository_Expecter) Create(ctx interface{}, r interface{}) *MockReviewRepository_Create_Call {
	return &MockReviewRepository_Create_Call{Call: _e.mock.On("Create", ctx, r)}
}

func (_c *MockReviewRepository_Create_Call) Run(run func(ctx context.Context, r *entity.Review)) *MockReviewRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Review))
	})
	return _c
}

func (_c *MockReviewRepository_Create_Call) Return(_a0 error) *MockReviewRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReviewRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Review) error) *MockReviewRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByOrderItemID provides a mock function with given fields: ctx, orderItemID
func (_m *MockReviewRepository) ExistsByOrderItemID(ctx context.Context, orderItemID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, orderItemID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByOrderItemID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, orderItemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, orderItemID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderItemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReviewRepository_ExistsByOrderItemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByOrderItemID'
type MockReviewRepository_ExistsByOrderItemID_Call struct {
	*mock.Call
}

// ExistsByOrderItemID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderItemID uuid.UUID
func (_e *MockReviewRepository_Expecter) ExistsByOrderItemID(ctx interface{}, orderItemID interface{}) *MockReviewRepository_ExistsByOrderItemID_Call {
	return &MockReviewRepository_ExistsByOrderItemID_Call{Call: _e.mock.On("ExistsByOrderItemID", ctx, orderItemID)}
}

func (_c *MockReviewRepository_ExistsByOrderItemID_Call) Run(run func(ctx context.Context, orderItemID uuid.UUID)) *MockReviewRepository_ExistsByOrderItemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockReviewRepository_ExistsByOrderItemID_Call) Return(_a0 bool, _a1 error) *MockReviewRepository_ExistsByOrderItemID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReviewRepository_ExistsByOrderItemID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *MockReviewRepository_ExistsByOrderItemID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByProduct provides a mock function with given fields: ctx, productID, rating, cursor, limit
func (_m *MockReviewRepository) ListByProduct(ctx context.Context, productID uuid.UUID, rating int, cursor string, limit int) ([]*entity.Review, string, error) {
	ret := _m.Called(ctx, productID, rating, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByProduct")
	}

	var r0 []*entity.Review
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, string, int) ([]*entity.Review, string, error)); ok {
		return rf(ctx, productID, rating, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, string, int) []*entity.Review); ok {
		r0 = rf(ctx, productID, rating, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Review)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, string, int) string); ok {
		r1 = rf(ctx, productID, rating, cursor, limit)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, string, int) error); ok {
		r2 = rf(ctx, productID, rating, cursor, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockReviewRepository_ListByProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByProduct'
type MockReviewRepository_ListByProduct_Call struct {
	*mock.Call
}

// ListByProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
//   - rating int
//   - cursor string
//   - limit int
func (_e *MockReviewRepository_Expecter) ListByProduct(ctx interface{}, productID interface{}, rating interface{}, cursor interface{}, limit interface{}) *MockReviewRepository_ListByProduct_Call {
	return &MockReviewRepository_ListByProduct_Call{Call: _e.mock.On("ListByProduct", ctx, productID, rating, cursor, limit)}
}

func (_c *MockReviewRepository_ListByProduct_Call) Run(run func(ctx context.Context, productID uuid.UUID, rating int, cursor string, limit int)) *MockReviewRepository_ListByProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockReviewRepository_ListByProduct_Call) Return(_a0 []*entity.Review, _a1 string, _a2 error) *MockReviewRepository_ListByProduct_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockReviewRepository_ListByProduct_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, string, int) ([]*entity.Review, string, error)) *MockReviewRepository_ListByProduct_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID, page, perPage
func (_m *MockReviewRepository) ListByUser(ctx context.Context, userID uuid.UUID, page int, perPage int) ([]*entity.Review, int, error) {
	ret := _m.Called(ctx, userID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*entity.Review
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*entity.Review, int, error)); ok {
		return rf(ctx, userID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*entity.Review); ok {
		r0 = rf(ctx, userID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Review)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, userID, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, userID, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockReviewRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockReviewRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - page int
//   - perPage int
func (_e *MockReviewRepository_Expecter) ListByUser(ctx interface{}, userID interface{}, page interface{}, perPage interface{}) *MockReviewRepository_ListByUser_Call {
	return &MockReviewRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, page, perPage)}
}

func (_c *MockReviewRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, page int, perPage int)) *MockReviewRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockReviewRepository_ListByUser_Call) Return(_a0 []*entity.Review, _a1 int, _a2 error) *MockReviewRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockReviewRepository_ListByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*entity.Review, int, error)) *MockReviewRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReviewRepository creates a new instance of MockReviewRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewRepository {
	mock := &MockReviewRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
