// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockAuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type MockAuditLogRepository struct {
	mock.Mock
}

type MockAuditLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogRepository) EXPECT() *MockAuditLogRepository_Expecter {
	return &MockAuditLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, a
func (_m *MockAuditLogRepository) Create(ctx context.Context, a *entity.AuditLog) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AuditLog) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuditLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - a *entity.AuditLog
func (_e *MockAuditLogRepository_Expecter) Create(ctx interface{}, a interface{}) *MockAuditLogRepository_Create_Call {
	return &MockAuditLogRepository_Create_Call{Call: _e.mock.On("Create", ctx, a)}
}

func (_c *MockAuditLogRepository_Create_Call) Run(run func(ctx context.Context, a *entity.AuditLog)) *MockAuditLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.AuditLog))
	})
	return _c
}

func (_c *MockAuditLogRepository_Create_Call) Return(_a0 error) *MockAuditLogRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditLogRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.AuditLog) error) *MockAuditLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, from, to, page, perPage
func (_m *MockAuditLogRepository) List(ctx context.Context, from time.Time, to time.Time, page int, perPage int) ([]*entity.AuditLog, int, error) {
	ret := _m.Called(ctx, from, to, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.AuditLog
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) ([]*entity.AuditLog, int, error)); ok {
		return rf(ctx, from, to, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) []*entity.AuditLog); ok {
		r0 = rf(ctx, from, to, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, int, int) int); ok {
		r1 = rf(ctx, from, to, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, time.Time, time.Time, int, int) error); ok {
		r2 = rf(ctx, from, to, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuditLogRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAuditLogRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
//   - page int
//   - perPage int
func (_e *MockAuditLogRepository_Expecter) List(ctx interface{}, from interface{}, to interface{}, page interface{}, perPage interface{}) *MockAuditLogRepository_List_Call {
	return &MockAuditLogRepository_List_Call{Call: _e.mock.On("List", ctx, from, to, page, perPage)}
}

func (_c *MockAuditLogRepository_List_Call) Run(run func(ctx context.Context, from time.Time, to time.Time, page int, perPage int)) *MockAuditLogRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockAuditLogRepository_List_Call) Return(_a0 []*entity.AuditLog, _a1 int, _a2 error) *MockAuditLogRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuditLogRepository_List_Call) RunAndReturn(run func(context.Context, time.Time, time.Time, int, int) ([]*entity.AuditLog, int, error)) *MockAuditLogRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLogRepository creates a new instance of MockAuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
