// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSupplierRepository is an autogenerated mock type for the SupplierRepository type
type MockSupplierRepository struct {
	mock.Mock
}

type MockSupplierRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSupplierRepository) EXPECT() *MockSupplierRepository_Expecter {
	return &MockSupplierRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, s
func (_m *MockSupplierRepository) Create(ctx context.Context, s *entity.Supplier) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Supplier) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupplierRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSupplierRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s *entity.Supplier
func (_e *MockSupplierRepository_Expecter) Create(ctx interface{}, s interface{}) *MockSupplierRepository_Create_Call {
	return &MockSupplierRepository_Create_Call{Call: _e.mock.On("Create", ctx, s)}
}

func (_c *MockSupplierRepository_Create_Call) Run(run func(ctx context.Context, s *entity.Supplier)) *MockSupplierRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Supplier))
	})
	return _c
}

func (_c *MockSupplierRepository_Create_Call) Return(_a0 error) *MockSupplierRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupplierRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Supplier) error) *MockSupplierRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockSupplierRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Supplier, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Supplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Supplier, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Supplier); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Supplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplierRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockSupplierRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSupplierRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockSupplierRepository_FindByID_Call {
	return &MockSupplierRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockSupplierRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSupplierRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSupplierRepository_FindByID_Call) Return(_a0 *entity.Supplier, _a1 error) *MockSupplierRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupplierRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Supplier, error)) *MockSupplierRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySlug provides a mock function with given fields: ctx, slug
func (_m *MockSupplierRepository) FindBySlug(ctx context.Context, slug string) (*entity.Supplier, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindBySlug")
	}

	var r0 *entity.Supplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Supplier, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Supplier); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Supplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplierRepository_FindBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySlug'
type MockSupplierRepository_FindBySlug_Call struct {
	*mock.Call
}

// FindBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockSupplierRepository_Expecter) FindBySlug(ctx interface{}, slug interface{}) *MockSupplierRepository_FindBySlug_Call {
	return &MockSupplierRepository_FindBySlug_Call{Call: _e.mock.On("FindBySlug", ctx, slug)}
}

func (_c *MockSupplierRepository_FindBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockSupplierRepository_FindBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSupplierRepository_FindBySlug_Call) Return(_a0 *entity.Supplier, _a1 error) *MockSupplierRepository_FindBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupplierRepository_FindBySlug_Call) RunAndReturn(run func(context.Context, string) (*entity.Supplier, error)) *MockSupplierRepository_FindBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *MockSupplierRepository) FindByUserID(ctx context.Context, userID uuid.UUID) (*entity.Supplier, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 *entity.Supplier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Supplier, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Supplier); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Supplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplierRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockSupplierRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockSupplierRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockSupplierRepository_FindByUserID_Call {
	return &MockSupplierRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockSupplierRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockSupplierRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSupplierRepository_FindByUserID_Call) Return(_a0 *entity.Supplier, _a1 error) *MockSupplierRepository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupplierRepository_FindByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Supplier, error)) *MockSupplierRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, status, q, page, perPage
func (_m *MockSupplierRepository) List(ctx context.Context, status string, q string, page int, perPage int) ([]*entity.Supplier, int, error) {
	ret := _m.Called(ctx, status, q, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Supplier
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]*entity.Supplier, int, error)); ok {
		return rf(ctx, status, q, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) []*entity.Supplier); ok {
		r0 = rf(ctx, status, q, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Supplier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) int); ok {
		r1 = rf(ctx, status, q, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int, int) error); ok {
		r2 = rf(ctx, status, q, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSupplierRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSupplierRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
//   - q string
//   - page int
//   - perPage int
func (_e *MockSupplierRepository_Expecter) List(ctx interface{}, status interface{}, q interface{}, page interface{}, perPage interface{}) *MockSupplierRepository_List_Call {
	return &MockSupplierRepository_List_Call{Call: _e.mock.On("List", ctx, status, q, page, perPage)}
}

func (_c *MockSupplierRepository_List_Call) Run(run func(ctx context.Context, status string, q string, page int, perPage int)) *MockSupplierRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockSupplierRepository_List_Call) Return(_a0 []*entity.Supplier, _a1 int, _a2 error) *MockSupplierRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSupplierRepository_List_Call) RunAndReturn(run func(context.Context, string, string, int, int) ([]*entity.Supplier, int, error)) *MockSupplierRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, s
func (_m *MockSupplierRepository) Update(ctx context.Context, s *entity.Supplier) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Supplier) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupplierRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSupplierRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - s *entity.Supplier
func (_e *MockSupplierRepository_Expecter) Update(ctx interface{}, s interface{}) *MockSupplierRepository_Update_Call {
	return &MockSupplierRepository_Update_Call{Call: _e.mock.On("Update", ctx, s)}
}

func (_c *MockSupplierRepository_Update_Call) Run(run func(ctx context.Context, s *entity.Supplier)) *MockSupplierRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Supplier))
	})
	return _c
}

func (_c *MockSupplierRepository_Update_Call) Return(_a0 error) *MockSupplierRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupplierRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Supplier) error) *MockSupplierRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSupplierRepository creates a new instance of MockSupplierRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSupplierRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSupplierRepository {
	mock := &MockSupplierRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
