// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockWithdrawRequestRepository is an autogenerated mock type for the WithdrawRequestRepository type
type MockWithdrawRequestRepository struct {
	mock.Mock
}

type MockWithdrawRequestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWithdrawRequestRepository) EXPECT() *MockWithdrawRequestRepository_Expecter {
	return &MockWithdrawRequestRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, w
func (_m *MockWithdrawRequestRepository) Create(ctx context.Context, w *entity.WithdrawRequest) error {
	ret := _m.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WithdrawRequest) error); ok {
		r0 = rf(ctx, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWithdrawRequestRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWithdrawRequestRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - w *entity.WithdrawRequest
func (_e *MockWithdrawRequestRepository_Expecter) Create(ctx interface{}, w interface{}) *MockWithdrawRequestRepository_Create_Call {
	return &MockWithdrawRequestRepository_Create_Call{Call: _e.mock.On("Create", ctx, w)}
}

func (_c *MockWithdrawRequestRepository_Create_Call) Run(run func(ctx context.Context, w *entity.WithdrawRequest)) *MockWithdrawRequestRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.WithdrawRequest))
	})
	return _c
}

func (_c *MockWithdrawRequestRepository_Create_Call) Return(_a0 error) *MockWithdrawRequestRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWithdrawRequestRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.WithdrawRequest) error) *MockWithdrawRequestRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockWithdrawRequestRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.WithdrawRequest, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.WithdrawRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.WithdrawRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.WithdrawRequest); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.WithdrawRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWithdrawRequestRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockWithdrawRequestRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockWithdrawRequestRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockWithdrawRequestRepository_FindByID_Call {
	return &MockWithdrawRequestRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockWithdrawRequestRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockWithdrawRequestRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockWithdrawRequestRepository_FindByID_Call) Return(_a0 *entity.WithdrawRequest, _a1 error) *MockWithdrawRequestRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWithdrawRequestRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.WithdrawRequest, error)) *MockWithdrawRequestRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function with given fields: ctx, status, page, perPage
func (_m *MockWithdrawRequestRepository) ListAll(ctx context.Context, status string, page int, perPage int) ([]*entity.WithdrawRequest, int, error) {
	ret := _m.Called(ctx, status, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []*entity.WithdrawRequest
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*entity.WithdrawRequest, int, error)); ok {
		return rf(ctx, status, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*entity.WithdrawRequest); ok {
		r0 = rf(ctx, status, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.WithdrawRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, status, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, status, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockWithdrawRequestRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockWithdrawRequestRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
//   - page int
//   - perPage int
func (_e *MockWithdrawRequestRepository_Expecter) ListAll(ctx interface{}, status interface{}, page interface{}, perPage interface{}) *MockWithdrawRequestRepository_ListAll_Call {
	return &MockWithdrawRequestRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx, status, page, perPage)}
}

func (_c *MockWithdrawRequestRepository_ListAll_Call) Run(run func(ctx context.Context, status string, page int, perPage int)) *MockWithdrawRequestRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockWithdrawRequestRepository_ListAll_Call) Return(_a0 []*entity.WithdrawRequest, _a1 int, _a2 error) *MockWithdrawRequestRepository_ListAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockWithdrawRequestRepository_ListAll_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*entity.WithdrawRequest, int, error)) *MockWithdrawRequestRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// ListBySupplier provides a mock function with given fields: ctx, supplierID, page, perPage
func (_m *MockWithdrawRequestRepository) ListBySupplier(ctx context.Context, supplierID uuid.UUID, page int, perPage int) ([]*entity.WithdrawRequest, int, error) {
	ret := _m.Called(ctx, supplierID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for ListBySupplier")
	}

	var r0 []*entity.WithdrawRequest
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*entity.WithdrawRequest, int, error)); ok {
		return rf(ctx, supplierID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*entity.WithdrawRequest); ok {
		r0 = rf(ctx, supplierID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.WithdrawRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, supplierID, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, supplierID, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockWithdrawRequestRepository_ListBySupplier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBySupplier'
type MockWithdrawRequestRepository_ListBySupplier_Call struct {
	*mock.Call
}

// ListBySupplier is a helper method to define mock.On call
//   - ctx context.Context
//   - supplierID uuid.UUID
//   - page int
//   - perPage int
func (_e *MockWithdrawRequestRepository_Expecter) ListBySupplier(ctx interface{}, supplierID interface{}, page interface{}, perPage interface{}) *MockWithdrawRequestRepository_ListBySupplier_Call {
	return &MockWithdrawRequestRepository_ListBySupplier_Call{Call: _e.mock.On("ListBySupplier", ctx, supplierID, page, perPage)}
}

func (_c *MockWithdrawRequestRepository_ListBySupplier_Call) Run(run func(ctx context.Context, supplierID uuid.UUID, page int, perPage int)) *MockWithdrawRequestRepository_ListBySupplier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockWithdrawRequestRepository_ListBySupplier_Call) Return(_a0 []*entity.WithdrawRequest, _a1 int, _a2 error) *MockWithdrawRequestRepository_ListBySupplier_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockWithdrawRequestRepository_ListBySupplier_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*entity.WithdrawRequest, int, error)) *MockWithdrawRequestRepository_ListBySupplier_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, w
func (_m *MockWithdrawRequestRepository) Update(ctx context.Context, w *entity.WithdrawRequest) error {
	ret := _m.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WithdrawRequest) error); ok {
		r0 = rf(ctx, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWithdrawRequestRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWithdrawRequestRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - w *entity.WithdrawRequest
func (_e *MockWithdrawRequestRepository_Expecter) Update(ctx interface{}, w interface{}) *MockWithdrawRequestRepository_Update_Call {
	return &MockWithdrawRequestRepository_Update_Call{Call: _e.mock.On("Update", ctx, w)}
}

func (_c *MockWithdrawRequestRepository_Update_Call) Run(run func(ctx context.Context, w *entity.WithdrawRequest)) *MockWithdrawRequestRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.WithdrawRequest))
	})
	return _c
}

func (_c *MockWithdrawRequestRepository_Update_Call) Return(_a0 error) *MockWithdrawRequestRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWithdrawRequestRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.WithdrawRequest) error) *MockWithdrawRequestRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWithdrawRequestRepository creates a new instance of MockWithdrawRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWithdrawRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWithdrawRequestRepository {
	mock := &MockWithdrawRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
