// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCartRepository is an autogenerated mock type for the CartRepository type
type MockCartRepository struct {
	mock.Mock
}

type MockCartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartRepository) EXPECT() *MockCartRepository_Expecter {
	return &MockCartRepository_Expecter{mock: &_m.Mock}
}

// FindItemByID provides a mock function with given fields: ctx, itemID
func (_m *MockCartRepository) FindItemByID(ctx context.Context, itemID uuid.UUID) (*entity.CartItem, error) {
	ret := _m.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for FindItemByID")
	}

	var r0 *entity.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.CartItem, error)); ok {
		return rf(ctx, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.CartItem); ok {
		r0 = rf(ctx, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CartItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCartRepository_FindItemByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindItemByID'
type MockCartRepository_FindItemByID_Call struct {
	*mock.Call
}

// FindItemByID is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID uuid.UUID
func (_e *MockCartRepository_Expecter) FindItemByID(ctx interface{}, itemID interface{}) *MockCartRepository_FindItemByID_Call {
	return &MockCartRepository_FindItemByID_Call{Call: _e.mock.On("FindItemByID", ctx, itemID)}
}

func (_c *MockCartRepository_FindItemByID_Call) Run(run func(ctx context.Context, itemID uuid.UUID)) *MockCartRepository_FindItemByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCartRepository_FindItemByID_Call) Return(_a0 *entity.CartItem, _a1 error) *MockCartRepository_FindItemByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCartRepository_FindItemByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.CartItem, error)) *MockCartRepository_FindItemByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrCreateByUserID provides a mock function with given fields: ctx, userID
func (_m *MockCartRepository) FindOrCreateByUserID(ctx context.Context, userID uuid.UUID) (*entity.Cart, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreateByUserID")
	}

	var r0 *entity.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Cart, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Cart); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCartRepository_FindOrCreateByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreateByUserID'
type MockCartRepository_FindOrCreateByUserID_Call struct {
	*mock.Call
}

// FindOrCreateByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCartRepository_Expecter) FindOrCreateByUserID(ctx interface{}, userID interface{}) *MockCartRepository_FindOrCreateByUserID_Call {
	return &MockCartRepository_FindOrCreateByUserID_Call{Call: _e.mock.On("FindOrCreateByUserID", ctx, userID)}
}

func (_c *MockCartRepository_FindOrCreateByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCartRepository_FindOrCreateByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCartRepository_FindOrCreateByUserID_Call) Return(_a0 *entity.Cart, _a1 error) *MockCartRepository_FindOrCreateByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCartRepository_FindOrCreateByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Cart, error)) *MockCartRepository_FindOrCreateByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListItemsByCartID provides a mock function with given fields: ctx, cartID
func (_m *MockCartRepository) ListItemsByCartID(ctx context.Context, cartID uuid.UUID) ([]*entity.CartItem, error) {
	ret := _m.Called(ctx, cartID)

	if len(ret) == 0 {
		panic("no return value specified for ListItemsByCartID")
	}

	var r0 []*entity.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.CartItem, error)); ok {
		return rf(ctx, cartID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.CartItem); ok {
		r0 = rf(ctx, cartID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.CartItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, cartID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCartRepository_ListItemsByCartID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItemsByCartID'
type MockCartRepository_ListItemsByCartID_Call struct {
	*mock.Call
}

// ListItemsByCartID is a helper method to define mock.On call
//   - ctx context.Context
//   - cartID uuid.UUID
func (_e *MockCartRepository_Expecter) ListItemsByCartID(ctx interface{}, cartID interface{}) *MockCartRepository_ListItemsByCartID_Call {
	return &MockCartRepository_ListItemsByCartID_Call{Call: _e.mock.On("ListItemsByCartID", ctx, cartID)}
}

func (_c *MockCartRepository_ListItemsByCartID_Call) Run(run func(ctx context.Context, cartID uuid.UUID)) *MockCartRepository_ListItemsByCartID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCartRepository_ListItemsByCartID_Call) Return(_a0 []*entity.CartItem, _a1 error) *MockCartRepository_ListItemsByCartID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCartRepository_ListItemsByCartID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.CartItem, error)) *MockCartRepository_ListItemsByCartID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveItem provides a mock function with given fields: ctx, itemID
func (_m *MockCartRepository) RemoveItem(ctx context.Context, itemID uuid.UUID) error {
	ret := _m.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, itemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartRepository_RemoveItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveItem'
type MockCartRepository_RemoveItem_Call struct {
	*mock.Call
}

// RemoveItem is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID uuid.UUID
func (_e *MockCartRepository_Expecter) RemoveItem(ctx interface{}, itemID interface{}) *MockCartRepository_RemoveItem_Call {
	return &MockCartRepository_RemoveItem_Call{Call: _e.mock.On("RemoveItem", ctx, itemID)}
}

func (_c *MockCartRepository_RemoveItem_Call) Run(run func(ctx context.Context, itemID uuid.UUID)) *MockCartRepository_RemoveItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCartRepository_RemoveItem_Call) Return(_a0 error) *MockCartRepository_RemoveItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartRepository_RemoveItem_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCartRepository_RemoveItem_Call {
	_c.Call.Return(run)
	return _c
}

// Touch provides a mock function with given fields: ctx, cartID
func (_m *MockCartRepository) Touch(ctx context.Context, cartID uuid.UUID) error {
	ret := _m.Called(ctx, cartID)

	if len(ret) == 0 {
		panic("no return value specified for Touch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, cartID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartRepository_Touch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Touch'
type MockCartRepository_Touch_Call struct {
	*mock.Call
}

// Touch is a helper method to define mock.On call
//   - ctx context.Context
//   - cartID uuid.UUID
func (_e *MockCartRepository_Expecter) Touch(ctx interface{}, cartID interface{}) *MockCartRepository_Touch_Call {
	return &MockCartRepository_Touch_Call{Call: _e.mock.On("Touch", ctx, cartID)}
}

func (_c *MockCartRepository_Touch_Call) Run(run func(ctx context.Context, cartID uuid.UUID)) *MockCartRepository_Touch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCartRepository_Touch_Call) Return(_a0 error) *MockCartRepository_Touch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartRepository_Touch_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCartRepository_Touch_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItemQty provides a mock function with given fields: ctx, itemID, qty
func (_m *MockCartRepository) UpdateItemQty(ctx context.Context, itemID uuid.UUID, qty int) error {
	ret := _m.Called(ctx, itemID, qty)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItemQty")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) error); ok {
		r0 = rf(ctx, itemID, qty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartRepository_UpdateItemQty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItemQty'
type MockCartRepository_UpdateItemQty_Call struct {
	*mock.Call
}

// UpdateItemQty is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID uuid.UUID
//   - qty int
func (_e *MockCartRepository_Expecter) UpdateItemQty(ctx interface{}, itemID interface{}, qty interface{}) *MockCartRepository_UpdateItemQty_Call {
	return &MockCartRepository_UpdateItemQty_Call{Call: _e.mock.On("UpdateItemQty", ctx, itemID, qty)}
}

func (_c *MockCartRepository_UpdateItemQty_Call) Run(run func(ctx context.Context, itemID uuid.UUID, qty int)) *MockCartRepository_UpdateItemQty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockCartRepository_UpdateItemQty_Call) Return(_a0 error) *MockCartRepository_UpdateItemQty_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartRepository_UpdateItemQty_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) error) *MockCartRepository_UpdateItemQty_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertItem provides a mock function with given fields: ctx, item
func (_m *MockCartRepository) UpsertItem(ctx context.Context, item *entity.CartItem) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for UpsertItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.CartItem) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartRepository_UpsertItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertItem'
type MockCartRepository_UpsertItem_Call struct {
	*mock.Call
}

// UpsertItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *entity.CartItem
func (_e *MockCartRepository_Expecter) UpsertItem(ctx interface{}, item interface{}) *MockCartRepository_UpsertItem_Call {
	return &MockCartRepository_UpsertItem_Call{Call: _e.mock.On("UpsertItem", ctx, item)}
}

func (_c *MockCartRepository_UpsertItem_Call) Run(run func(ctx context.Context, item *entity.CartItem)) *MockCartRepository_UpsertItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.CartItem))
	})
	return _c
}

func (_c *MockCartRepository_UpsertItem_Call) Return(_a0 error) *MockCartRepository_UpsertItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartRepository_UpsertItem_Call) RunAndReturn(run func(context.Context, *entity.CartItem) error) *MockCartRepository_UpsertItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCartRepository creates a new instance of MockCartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartRepository {
	mock := &MockCartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
