// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserAddressRepository is an autogenerated mock type for the UserAddressRepository type
type MockUserAddressRepository struct {
	mock.Mock
}

type MockUserAddressRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserAddressRepository) EXPECT() *MockUserAddressRepository_Expecter {
	return &MockUserAddressRepository_Expecter{mock: &_m.Mock}
}

// ClearDefault provides a mock function with given fields: ctx, userID, keepID
func (_m *MockUserAddressRepository) ClearDefault(ctx context.Context, userID uuid.UUID, keepID uuid.UUID) error {
	ret := _m.Called(ctx, userID, keepID)

	if len(ret) == 0 {
		panic("no return value specified for ClearDefault")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, keepID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserAddressRepository_ClearDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearDefault'
type MockUserAddressRepository_ClearDefault_Call struct {
	*mock.Call
}

// ClearDefault is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - keepID uuid.UUID
func (_e *MockUserAddressRepository_Expecter) ClearDefault(ctx interface{}, userID interface{}, keepID interface{}) *MockUserAddressRepository_ClearDefault_Call {
	return &MockUserAddressRepository_ClearDefault_Call{Call: _e.mock.On("ClearDefault", ctx, userID, keepID)}
}

func (_c *MockUserAddressRepository_ClearDefault_Call) Run(run func(ctx context.Context, userID uuid.UUID, keepID uuid.UUID)) *MockUserAddressRepository_ClearDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserAddressRepository_ClearDefault_Call) Return(_a0 error) *MockUserAddressRepository_ClearDefault_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserAddressRepository_ClearDefault_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockUserAddressRepository_ClearDefault_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, a
func (_m *MockUserAddressRepository) Create(ctx context.Context, a *entity.UserAddress) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserAddress) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserAddressRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserAddressRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - a *entity.UserAddress
func (_e *MockUserAddressRepository_Expecter) Create(ctx interface{}, a interface{}) *MockUserAddressRepository_Create_Call {
	return &MockUserAddressRepository_Create_Call{Call: _e.mock.On("Create", ctx, a)}
}

func (_c *MockUserAddressRepository_Create_Call) Run(run func(ctx context.Context, a *entity.UserAddress)) *MockUserAddressRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserAddress))
	})
	return _c
}

func (_c *MockUserAddressRepository_Create_Call) Return(_a0 error) *MockUserAddressRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserAddressRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.UserAddress) error) *MockUserAddressRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockUserAddressRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserAddressRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserAddressRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserAddressRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockUserAddressRepository_Delete_Call {
	return &MockUserAddressRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserAddressRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserAddressRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserAddressRepository_Delete_Call) Return(_a0 error) *MockUserAddressRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserAddressRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockUserAddressRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockUserAddressRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.UserAddress, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.UserAddress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.UserAddress, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.UserAddress); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserAddress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserAddressRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserAddressRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserAddressRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockUserAddressRepository_FindByID_Call {
	return &MockUserAddressRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockUserAddressRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserAddressRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserAddressRepository_FindByID_Call) Return(_a0 *entity.UserAddress, _a1 error) *MockUserAddressRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserAddressRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.UserAddress, error)) *MockUserAddressRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *MockUserAddressRepository) ListByUserID(ctx context.Context, userID uuid.UUID) ([]*entity.UserAddress, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*entity.UserAddress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.UserAddress, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.UserAddress); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserAddress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserAddressRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockUserAddressRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserAddressRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}) *MockUserAddressRepository_ListByUserID_Call {
	return &MockUserAddressRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *MockUserAddressRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserAddressRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserAddressRepository_ListByUserID_Call) Return(_a0 []*entity.UserAddress, _a1 error) *MockUserAddressRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserAddressRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.UserAddress, error)) *MockUserAddressRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, a
func (_m *MockUserAddressRepository) Update(ctx context.Context, a *entity.UserAddress) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserAddress) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserAddressRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserAddressRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - a *entity.UserAddress
func (_e *MockUserAddressRepository_Expecter) Update(ctx interface{}, a interface{}) *MockUserAddressRepository_Update_Call {
	return &MockUserAddressRepository_Update_Call{Call: _e.mock.On("Update", ctx, a)}
}

func (_c *MockUserAddressRepository_Update_Call) Run(run func(ctx context.Context, a *entity.UserAddress)) *MockUserAddressRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserAddress))
	})
	return _c
}

func (_c *MockUserAddressRepository_Update_Call) Return(_a0 error) *MockUserAddressRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserAddressRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.UserAddress) error) *MockUserAddressRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserAddressRepository creates a new instance of MockUserAddressRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserAddressRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserAddressRepository {
	mock := &MockUserAddressRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
