// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockProductImageRepository is an autogenerated mock type for the ProductImageRepository type
type MockProductImageRepository struct {
	mock.Mock
}

type MockProductImageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductImageRepository) EXPECT() *MockProductImageRepository_Expecter {
	return &MockProductImageRepository_Expecter{mock: &_m.Mock}
}

// CountByProductID provides a mock function with given fields: ctx, productID
func (_m *MockProductImageRepository) CountByProductID(ctx context.Context, productID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for CountByProductID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductImageRepository_CountByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByProductID'
type MockProductImageRepository_CountByProductID_Call struct {
	*mock.Call
}

// CountByProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockProductImageRepository_Expecter) CountByProductID(ctx interface{}, productID interface{}) *MockProductImageRepository_CountByProductID_Call {
	return &MockProductImageRepository_CountByProductID_Call{Call: _e.mock.On("CountByProductID", ctx, productID)}
}

func (_c *MockProductImageRepository_CountByProductID_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockProductImageRepository_CountByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductImageRepository_CountByProductID_Call) Return(_a0 int, _a1 error) *MockProductImageRepository_CountByProductID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductImageRepository_CountByProductID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockProductImageRepository_CountByProductID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, img
func (_m *MockProductImageRepository) Create(ctx context.Context, img *entity.ProductImage) error {
	ret := _m.Called(ctx, img)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ProductImage) error); ok {
		r0 = rf(ctx, img)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductImageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductImageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - img *entity.ProductImage
func (_e *MockProductImageRepository_Expecter) Create(ctx interface{}, img interface{}) *MockProductImageRepository_Create_Call {
	return &MockProductImageRepository_Create_Call{Call: _e.mock.On("Create", ctx, img)}
}

func (_c *MockProductImageRepository_Create_Call) Run(run func(ctx context.Context, img *entity.ProductImage)) *MockProductImageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.ProductImage))
	})
	return _c
}

func (_c *MockProductImageRepository_Create_Call) Return(_a0 error) *MockProductImageRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductImageRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.ProductImage) error) *MockProductImageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockProductImageRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductImageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductImageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProductImageRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockProductImageRepository_Delete_Call {
	return &MockProductImageRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockProductImageRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProductImageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductImageRepository_Delete_Call) Return(_a0 error) *MockProductImageRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductImageRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockProductImageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockProductImageRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.ProductImage, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.ProductImage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.ProductImage, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.ProductImage); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ProductImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductImageRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockProductImageRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProductImageRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockProductImageRepository_FindByID_Call {
	return &MockProductImageRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockProductImageRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProductImageRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductImageRepository_FindByID_Call) Return(_a0 *entity.ProductImage, _a1 error) *MockProductImageRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductImageRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.ProductImage, error)) *MockProductImageRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPrimary provides a mock function with given fields: ctx, productID
func (_m *MockProductImageRepository) FindPrimary(ctx context.Context, productID uuid.UUID) (*entity.ProductImage, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for FindPrimary")
	}

	var r0 *entity.ProductImage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.ProductImage, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.ProductImage); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ProductImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductImageRepository_FindPrimary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPrimary'
type MockProductImageRepository_FindPrimary_Call struct {
	*mock.Call
}

// FindPrimary is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockProductImageRepository_Expecter) FindPrimary(ctx interface{}, productID interface{}) *MockProductImageRepository_FindPrimary_Call {
	return &MockProductImageRepository_FindPrimary_Call{Call: _e.mock.On("FindPrimary", ctx, productID)}
}

func (_c *MockProductImageRepository_FindPrimary_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockProductImageRepository_FindPrimary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductImageRepository_FindPrimary_Call) Return(_a0 *entity.ProductImage, _a1 error) *MockProductImageRepository_FindPrimary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductImageRepository_FindPrimary_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.ProductImage, error)) *MockProductImageRepository_FindPrimary_Call {
	_c.Call.Return(run)
	return _c
}

// ListByProductID provides a mock function with given fields: ctx, productID
func (_m *MockProductImageRepository) ListByProductID(ctx context.Context, productID uuid.UUID) ([]*entity.ProductImage, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for ListByProductID")
	}

	var r0 []*entity.ProductImage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.ProductImage, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.ProductImage); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ProductImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductImageRepository_ListByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByProductID'
type MockProductImageRepository_ListByProductID_Call struct {
	*mock.Call
}

// ListByProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockProductImageRepository_Expecter) ListByProductID(ctx interface{}, productID interface{}) *MockProductImageRepository_ListByProductID_Call {
	return &MockProductImageRepository_ListByProductID_Call{Call: _e.mock.On("ListByProductID", ctx, productID)}
}

func (_c *MockProductImageRepository_ListByProductID_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockProductImageRepository_ListByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductImageRepository_ListByProductID_Call) Return(_a0 []*entity.ProductImage, _a1 error) *MockProductImageRepository_ListByProductID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductImageRepository_ListByProductID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.ProductImage, error)) *MockProductImageRepository_ListByProductID_Call {
	_c.Call.Return(run)
	return _c
}

// SetPrimary provides a mock function with given fields: ctx, id
func (_m *MockProductImageRepository) SetPrimary(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SetPrimary")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductImageRepository_SetPrimary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPrimary'
type MockProductImageRepository_SetPrimary_Call struct {
	*mock.Call
}

// SetPrimary is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProductImageRepository_Expecter) SetPrimary(ctx interface{}, id interface{}) *MockProductImageRepository_SetPrimary_Call {
	return &MockProductImageRepository_SetPrimary_Call{Call: _e.mock.On("SetPrimary", ctx, id)}
}

func (_c *MockProductImageRepository_SetPrimary_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProductImageRepository_SetPrimary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductImageRepository_SetPrimary_Call) Return(_a0 error) *MockProductImageRepository_SetPrimary_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductImageRepository_SetPrimary_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockProductImageRepository_SetPrimary_Call {
	_c.Call.Return(run)
	return _c
}

// UnsetPrimary provides a mock function with given fields: ctx, productID
func (_m *MockProductImageRepository) UnsetPrimary(ctx context.Context, productID uuid.UUID) error {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for UnsetPrimary")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductImageRepository_UnsetPrimary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsetPrimary'
type MockProductImageRepository_UnsetPrimary_Call struct {
	*mock.Call
}

// UnsetPrimary is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockProductImageRepository_Expecter) UnsetPrimary(ctx interface{}, productID interface{}) *MockProductImageRepository_UnsetPrimary_Call {
	return &MockProductImageRepository_UnsetPrimary_Call{Call: _e.mock.On("UnsetPrimary", ctx, productID)}
}

func (_c *MockProductImageRepository_UnsetPrimary_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockProductImageRepository_UnsetPrimary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductImageRepository_UnsetPrimary_Call) Return(_a0 error) *MockProductImageRepository_UnsetPrimary_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductImageRepository_UnsetPrimary_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockProductImageRepository_UnsetPrimary_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductImageRepository creates a new instance of MockProductImageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductImageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductImageRepository {
	mock := &MockProductImageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
