// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "erdinhrmwn/bangunin/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockWishlistRepository is an autogenerated mock type for the WishlistRepository type
type MockWishlistRepository struct {
	mock.Mock
}

type MockWishlistRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWishlistRepository) EXPECT() *MockWishlistRepository_Expecter {
	return &MockWishlistRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, w
func (_m *MockWishlistRepository) Create(ctx context.Context, w *entity.Wishlist) error {
	ret := _m.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Wishlist) error); ok {
		r0 = rf(ctx, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWishlistRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWishlistRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - w *entity.Wishlist
func (_e *MockWishlistRepository_Expecter) Create(ctx interface{}, w interface{}) *MockWishlistRepository_Create_Call {
	return &MockWishlistRepository_Create_Call{Call: _e.mock.On("Create", ctx, w)}
}

func (_c *MockWishlistRepository_Create_Call) Run(run func(ctx context.Context, w *entity.Wishlist)) *MockWishlistRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Wishlist))
	})
	return _c
}

func (_c *MockWishlistRepository_Create_Call) Return(_a0 error) *MockWishlistRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWishlistRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Wishlist) error) *MockWishlistRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, productID
func (_m *MockWishlistRepository) Delete(ctx context.Context, userID uuid.UUID, productID uuid.UUID) error {
	ret := _m.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWishlistRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWishlistRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - productID uuid.UUID
func (_e *MockWishlistRepository_Expecter) Delete(ctx interface{}, userID interface{}, productID interface{}) *MockWishlistRepository_Delete_Call {
	return &MockWishlistRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, productID)}
}

func (_c *MockWishlistRepository_Delete_Call) Run(run func(ctx context.Context, userID uuid.UUID, productID uuid.UUID)) *MockWishlistRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockWishlistRepository_Delete_Call) Return(_a0 error) *MockWishlistRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWishlistRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockWishlistRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByUserAndProduct provides a mock function with given fields: ctx, userID, productID
func (_m *MockWishlistRepository) ExistsByUserAndProduct(ctx context.Context, userID uuid.UUID, productID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByUserAndProduct")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, userID, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, userID, productID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWishlistRepository_ExistsByUserAndProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByUserAndProduct'
type MockWishlistRepository_ExistsByUserAndProduct_Call struct {
	*mock.Call
}

// ExistsByUserAndProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - productID uuid.UUID
func (_e *MockWishlistRepository_Expecter) ExistsByUserAndProduct(ctx interface{}, userID interface{}, productID interface{}) *MockWishlistRepository_ExistsByUserAndProduct_Call {
	return &MockWishlistRepository_ExistsByUserAndProduct_Call{Call: _e.mock.On("ExistsByUserAndProduct", ctx, userID, productID)}
}

func (_c *MockWishlistRepository_ExistsByUserAndProduct_Call) Run(run func(ctx context.Context, userID uuid.UUID, productID uuid.UUID)) *MockWishlistRepository_ExistsByUserAndProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockWishlistRepository_ExistsByUserAndProduct_Call) Return(_a0 bool, _a1 error) *MockWishlistRepository_ExistsByUserAndProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWishlistRepository_ExistsByUserAndProduct_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockWishlistRepository_ExistsByUserAndProduct_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID, page, perPage
func (_m *MockWishlistRepository) ListByUser(ctx context.Context, userID uuid.UUID, page int, perPage int) ([]*entity.Wishlist, int, error) {
	ret := _m.Called(ctx, userID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*entity.Wishlist
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*entity.Wishlist, int, error)); ok {
		return rf(ctx, userID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*entity.Wishlist); ok {
		r0 = rf(ctx, userID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Wishlist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, userID, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, userID, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockWishlistRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockWishlistRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - page int
//   - perPage int
func (_e *MockWishlistRepository_Expecter) ListByUser(ctx interface{}, userID interface{}, page interface{}, perPage interface{}) *MockWishlistRepository_ListByUser_Call {
	return &MockWishlistRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, page, perPage)}
}

func (_c *MockWishlistRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, page int, perPage int)) *MockWishlistRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockWishlistRepository_ListByUser_Call) Return(_a0 []*entity.Wishlist, _a1 int, _a2 error) *MockWishlistRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockWishlistRepository_ListByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*entity.Wishlist, int, error)) *MockWishlistRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWishlistRepository creates a new instance of MockWishlistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWishlistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWishlistRepository {
	mock := &MockWishlistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
