// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockEmailEnqueuer is an autogenerated mock type for the EmailEnqueuer type
type MockEmailEnqueuer struct {
	mock.Mock
}

type MockEmailEnqueuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailEnqueuer) EXPECT() *MockEmailEnqueuer_Expecter {
	return &MockEmailEnqueuer_Expecter{mock: &_m.Mock}
}

// EnqueueEmail provides a mock function with given fields: to, subject, body
func (_m *MockEmailEnqueuer) EnqueueEmail(to string, subject string, body string) error {
	ret := _m.Called(to, subject, body)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(to, subject, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailEnqueuer_EnqueueEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueEmail'
type MockEmailEnqueuer_EnqueueEmail_Call struct {
	*mock.Call
}

// EnqueueEmail is a helper method to define mock.On call
//   - to string
//   - subject string
//   - body string
func (_e *MockEmailEnqueuer_Expecter) EnqueueEmail(to interface{}, subject interface{}, body interface{}) *MockEmailEnqueuer_EnqueueEmail_Call {
	return &MockEmailEnqueuer_EnqueueEmail_Call{Call: _e.mock.On("EnqueueEmail", to, subject, body)}
}

func (_c *MockEmailEnqueuer_EnqueueEmail_Call) Run(run func(to string, subject string, body string)) *MockEmailEnqueuer_EnqueueEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockEmailEnqueuer_EnqueueEmail_Call) Return(_a0 error) *MockEmailEnqueuer_EnqueueEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailEnqueuer_EnqueueEmail_Call) RunAndReturn(run func(string, string, string) error) *MockEmailEnqueuer_EnqueueEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailEnqueuer creates a new instance of MockEmailEnqueuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailEnqueuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailEnqueuer {
	mock := &MockEmailEnqueuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
