// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockReportEnqueuer is an autogenerated mock type for the ReportEnqueuer type
type MockReportEnqueuer struct {
	mock.Mock
}

type MockReportEnqueuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportEnqueuer) EXPECT() *MockReportEnqueuer_Expecter {
	return &MockReportEnqueuer_Expecter{mock: &_m.Mock}
}

// EnqueueAdminReportGenerate provides a mock function with given fields: adminID, from, to
func (_m *MockReportEnqueuer) EnqueueAdminReportGenerate(adminID uuid.UUID, from time.Time, to time.Time) error {
	ret := _m.Called(adminID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueAdminReportGenerate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r0 = rf(adminID, from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportEnqueuer_EnqueueAdminReportGenerate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueAdminReportGenerate'
type MockReportEnqueuer_EnqueueAdminReportGenerate_Call struct {
	*mock.Call
}

// EnqueueAdminReportGenerate is a helper method to define mock.On call
//   - adminID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockReportEnqueuer_Expecter) EnqueueAdminReportGenerate(adminID interface{}, from interface{}, to interface{}) *MockReportEnqueuer_EnqueueAdminReportGenerate_Call {
	return &MockReportEnqueuer_EnqueueAdminReportGenerate_Call{Call: _e.mock.On("EnqueueAdminReportGenerate", adminID, from, to)}
}

func (_c *MockReportEnqueuer_EnqueueAdminReportGenerate_Call) Run(run func(adminID uuid.UUID, from time.Time, to time.Time)) *MockReportEnqueuer_EnqueueAdminReportGenerate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockReportEnqueuer_EnqueueAdminReportGenerate_Call) Return(_a0 error) *MockReportEnqueuer_EnqueueAdminReportGenerate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportEnqueuer_EnqueueAdminReportGenerate_Call) RunAndReturn(run func(uuid.UUID, time.Time, time.Time) error) *MockReportEnqueuer_EnqueueAdminReportGenerate_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueueReportGenerate provides a mock function with given fields: supplierID, from, to
func (_m *MockReportEnqueuer) EnqueueReportGenerate(supplierID uuid.UUID, from time.Time, to time.Time) error {
	ret := _m.Called(supplierID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueReportGenerate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time) error); ok {
		r0 = rf(supplierID, from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportEnqueuer_EnqueueReportGenerate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueReportGenerate'
type MockReportEnqueuer_EnqueueReportGenerate_Call struct {
	*mock.Call
}

// EnqueueReportGenerate is a helper method to define mock.On call
//   - supplierID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockReportEnqueuer_Expecter) EnqueueReportGenerate(supplierID interface{}, from interface{}, to interface{}) *MockReportEnqueuer_EnqueueReportGenerate_Call {
	return &MockReportEnqueuer_EnqueueReportGenerate_Call{Call: _e.mock.On("EnqueueReportGenerate", supplierID, from, to)}
}

func (_c *MockReportEnqueuer_EnqueueReportGenerate_Call) Run(run func(supplierID uuid.UUID, from time.Time, to time.Time)) *MockReportEnqueuer_EnqueueReportGenerate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockReportEnqueuer_EnqueueReportGenerate_Call) Return(_a0 error) *MockReportEnqueuer_EnqueueReportGenerate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportEnqueuer_EnqueueReportGenerate_Call) RunAndReturn(run func(uuid.UUID, time.Time, time.Time) error) *MockReportEnqueuer_EnqueueReportGenerate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportEnqueuer creates a new instance of MockReportEnqueuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportEnqueuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportEnqueuer {
	mock := &MockReportEnqueuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
