// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockMediaEnqueuer is an autogenerated mock type for the MediaEnqueuer type
type MockMediaEnqueuer struct {
	mock.Mock
}

type MockMediaEnqueuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaEnqueuer) EXPECT() *MockMediaEnqueuer_Expecter {
	return &MockMediaEnqueuer_Expecter{mock: &_m.Mock}
}

// EnqueueMediaProcess provides a mock function with given fields: key
func (_m *MockMediaEnqueuer) EnqueueMediaProcess(key string) error {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueMediaProcess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaEnqueuer_EnqueueMediaProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueMediaProcess'
type MockMediaEnqueuer_EnqueueMediaProcess_Call struct {
	*mock.Call
}

// EnqueueMediaProcess is a helper method to define mock.On call
//   - key string
func (_e *MockMediaEnqueuer_Expecter) EnqueueMediaProcess(key interface{}) *MockMediaEnqueuer_EnqueueMediaProcess_Call {
	return &MockMediaEnqueuer_EnqueueMediaProcess_Call{Call: _e.mock.On("EnqueueMediaProcess", key)}
}

func (_c *MockMediaEnqueuer_EnqueueMediaProcess_Call) Run(run func(key string)) *MockMediaEnqueuer_EnqueueMediaProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMediaEnqueuer_EnqueueMediaProcess_Call) Return(_a0 error) *MockMediaEnqueuer_EnqueueMediaProcess_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaEnqueuer_EnqueueMediaProcess_Call) RunAndReturn(run func(string) error) *MockMediaEnqueuer_EnqueueMediaProcess_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaEnqueuer creates a new instance of MockMediaEnqueuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaEnqueuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaEnqueuer {
	mock := &MockMediaEnqueuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
