// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockStorageService is an autogenerated mock type for the StorageService type
type MockStorageService struct {
	mock.Mock
}

type MockStorageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageService) EXPECT() *MockStorageService_Expecter {
	return &MockStorageService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockStorageService) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorageService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorageService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageService_Expecter) Delete(ctx interface{}, key interface{}) *MockStorageService_Delete_Call {
	return &MockStorageService_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockStorageService_Delete_Call) Run(run func(ctx context.Context, key string)) *MockStorageService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorageService_Delete_Call) Return(_a0 error) *MockStorageService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockStorageService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, key, r, size, contentType
func (_m *MockStorageService) Upload(ctx context.Context, key string, r io.Reader, size int64, contentType string) (string, error) {
	ret := _m.Called(ctx, key, r, size, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) (string, error)); ok {
		return rf(ctx, key, r, size, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) string); ok {
		r0 = rf(ctx, key, r, size, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, int64, string) error); ok {
		r1 = rf(ctx, key, r, size, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorageService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockStorageService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - r io.Reader
//   - size int64
//   - contentType string
func (_e *MockStorageService_Expecter) Upload(ctx interface{}, key interface{}, r interface{}, size interface{}, contentType interface{}) *MockStorageService_Upload_Call {
	return &MockStorageService_Upload_Call{Call: _e.mock.On("Upload", ctx, key, r, size, contentType)}
}

func (_c *MockStorageService_Upload_Call) Run(run func(ctx context.Context, key string, r io.Reader, size int64, contentType string)) *MockStorageService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *MockStorageService_Upload_Call) Return(url string, err error) *MockStorageService_Upload_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *MockStorageService_Upload_Call) RunAndReturn(run func(context.Context, string, io.Reader, int64, string) (string, error)) *MockStorageService_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorageService creates a new instance of MockStorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageService {
	mock := &MockStorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
