// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	service "erdinhrmwn/bangunin/internal/domain/service"

	mock "github.com/stretchr/testify/mock"
)

// MockShippingGateway is an autogenerated mock type for the ShippingGateway type
type MockShippingGateway struct {
	mock.Mock
}

type MockShippingGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShippingGateway) EXPECT() *MockShippingGateway_Expecter {
	return &MockShippingGateway_Expecter{mock: &_m.Mock}
}

// GetCost provides a mock function with given fields: ctx, originCityID, destCityID, weightGram
func (_m *MockShippingGateway) GetCost(ctx context.Context, originCityID int, destCityID int, weightGram int) ([]service.ShippingOption, error) {
	ret := _m.Called(ctx, originCityID, destCityID, weightGram)

	if len(ret) == 0 {
		panic("no return value specified for GetCost")
	}

	var r0 []service.ShippingOption
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]service.ShippingOption, error)); ok {
		return rf(ctx, originCityID, destCityID, weightGram)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []service.ShippingOption); ok {
		r0 = rf(ctx, originCityID, destCityID, weightGram)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.ShippingOption)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, originCityID, destCityID, weightGram)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockShippingGateway_GetCost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCost'
type MockShippingGateway_GetCost_Call struct {
	*mock.Call
}

// GetCost is a helper method to define mock.On call
//   - ctx context.Context
//   - originCityID int
//   - destCityID int
//   - weightGram int
func (_e *MockShippingGateway_Expecter) GetCost(ctx interface{}, originCityID interface{}, destCityID interface{}, weightGram interface{}) *MockShippingGateway_GetCost_Call {
	return &MockShippingGateway_GetCost_Call{Call: _e.mock.On("GetCost", ctx, originCityID, destCityID, weightGram)}
}

func (_c *MockShippingGateway_GetCost_Call) Run(run func(ctx context.Context, originCityID int, destCityID int, weightGram int)) *MockShippingGateway_GetCost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockShippingGateway_GetCost_Call) Return(_a0 []service.ShippingOption, _a1 error) *MockShippingGateway_GetCost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockShippingGateway_GetCost_Call) RunAndReturn(run func(context.Context, int, int, int) ([]service.ShippingOption, error)) *MockShippingGateway_GetCost_Call {
	_c.Call.Return(run)
	return _c
}

// TrackWaybill provides a mock function with given fields: ctx, waybill
func (_m *MockShippingGateway) TrackWaybill(ctx context.Context, waybill string) (*service.TrackInfo, error) {
	ret := _m.Called(ctx, waybill)

	if len(ret) == 0 {
		panic("no return value specified for TrackWaybill")
	}

	var r0 *service.TrackInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*service.TrackInfo, error)); ok {
		return rf(ctx, waybill)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *service.TrackInfo); ok {
		r0 = rf(ctx, waybill)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.TrackInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, waybill)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockShippingGateway_TrackWaybill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrackWaybill'
type MockShippingGateway_TrackWaybill_Call struct {
	*mock.Call
}

// TrackWaybill is a helper method to define mock.On call
//   - ctx context.Context
//   - waybill string
func (_e *MockShippingGateway_Expecter) TrackWaybill(ctx interface{}, waybill interface{}) *MockShippingGateway_TrackWaybill_Call {
	return &MockShippingGateway_TrackWaybill_Call{Call: _e.mock.On("TrackWaybill", ctx, waybill)}
}

func (_c *MockShippingGateway_TrackWaybill_Call) Run(run func(ctx context.Context, waybill string)) *MockShippingGateway_TrackWaybill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockShippingGateway_TrackWaybill_Call) Return(_a0 *service.TrackInfo, _a1 error) *MockShippingGateway_TrackWaybill_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockShippingGateway_TrackWaybill_Call) RunAndReturn(run func(context.Context, string) (*service.TrackInfo, error)) *MockShippingGateway_TrackWaybill_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockShippingGateway creates a new instance of MockShippingGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShippingGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShippingGateway {
	mock := &MockShippingGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
